import { StyleSheet } from "react-native";
import { createCompatStyleSheet } from "../../lib/crossPlatformStyles";
import {
  ACTION_SUCCESS_COLOR,
  ACTION_SUCCESS_FOREGROUND,
  LEAGUE_HEADER_ARABIC_FONT_FAMILY,
  MONO_FONT,
} from "./leagues.constants";

export const styles = createCompatStyleSheet({
  leagueTopHeader: {
    backgroundColor: "#020202",
    position: "relative",
    zIndex: 3,
  },
  leagueTopHeaderBlend: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 22,
  },
  leagueTopHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 48,
  },
  leagueTopHeaderLogoWrap: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    paddingHorizontal: 0,
  },
  leagueTopHeaderLogoImage: {
    backgroundColor: "transparent",
  },
  leagueTopHeaderTabsRow: {
    flex: 1,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    marginLeft: 2,
    marginRight: 0,
  },
  leagueTopHeaderTabGroup: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  leagueTopHeaderTab: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 2,
    minHeight: 36,
  },
  leagueTopHeaderTabDivider: {
    width: 1,
    height: 16,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginHorizontal: 6,
    borderRadius: 999,
  },
  leagueTopHeaderTabText: {
    color: "rgba(255,255,255,0.84)",
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: -0.35,
    textShadowColor: "rgba(255,255,255,0.14)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  leagueTopHeaderTabTextActive: {
    color: "#FFFFFF",
  },
  leagueTopHeaderTabUnderline: {
    width: 14,
    height: 2,
    borderRadius: 999,
    backgroundColor: "transparent",
    marginTop: 4,
  },
  leagueTopHeaderTabUnderlineActive: {
    width: 20,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  leagueTopHeaderNotificationButton: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  leagueTopHeaderNotificationBadge: {
    position: "absolute",
    top: 1,
    right: -1,
    backgroundColor: "#E30015",
    borderWidth: 1,
    borderColor: "#020202",
  },
  root: {
    flex: 1,
    backgroundColor: "#05070D",
  },
  leaguesListHeader: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#05070D",
    zIndex: 20,
    elevation: 14,
    position: "relative",
    overflow: "visible",
  },
  leaguesListHeaderRow: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 38,
  },
  leaguesListHeaderSpacer: {
    width: 88,
    height: 34,
  },
  leaguesListHeaderCenterBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  leaguesListVarAnchor: {
    position: "absolute",
    top: 10,
    right: -28,
    width: 312,
    alignItems: "flex-end",
    zIndex: 24,
  },
  leaguesListTitleBlock: {
    flex: 1,
    alignItems: "flex-end",
    marginLeft: 12,
  },
  leaguesListKicker: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 10,
    fontWeight: "800",
    fontFamily: MONO_FONT,
  },
  leaguesListTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
  },
  leaguesListTitleCentered: {
    textAlign: "center",
    marginTop: 1,
    fontSize: 24,
    lineHeight: 28,
  },
  leaguesListLogoWrap: {
    width: 92,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  leaguesListLogoImage: {
    width: 78,
    height: 28,
  },
  leaguesListVarTrigger: {
    width: 104,
    height: 40,
    borderTopLeftRadius: 11,
    borderBottomLeftRadius: 11,
    borderTopRightRadius: 7,
    borderBottomRightRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 14,
    paddingRight: 22,
    backgroundColor: "#F5F5F2",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 10,
  },
  leaguesListVarTriggerActive: {
    borderWidth: 1,
    borderColor: "rgba(11,13,18,0.08)",
    backgroundColor: "#FFFFFF",
  },
  leaguesListVarTriggerPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  leaguesListVarTriggerImage: {
    width: 70,
    height: 24,
    tintColor: "#0B0D12",
  },
  leaguesListDrawerWrap: {
    width: 286,
    marginTop: 22,
    marginRight: 18,
    zIndex: 26,
    elevation: 16,
  },
  leaguesListDrawerScroll: {
    flexGrow: 0,
  },
  leaguesListDrawerContent: {
    paddingTop: 4,
    paddingBottom: 18,
  },
  leaguesListDrawerItemWrap: {
    marginBottom: 8,
  },
  leaguesListDrawerItem: {
    minHeight: 68,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "#071018",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 12,
  },
  leaguesListDrawerItemActive: {
    backgroundColor: "#0B1620",
    borderColor: "rgba(255,255,255,0.18)",
  },
  leaguesListDrawerAccentLine: {
    width: 0,
    alignSelf: "stretch",
    borderRadius: 999,
    marginRight: 0,
  },
  leaguesListDrawerTextBlock: {
    flex: 1,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  leaguesListDrawerTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  leaguesListDrawerSummary: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 5,
  },
  leaguesListDrawerIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
    borderWidth: 1,
  },
  leaguesListDrawerIconImage: {
    width: 30,
    height: 30,
  },
  screenContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 128,
  },
  matchDetailOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#05070D",
    zIndex: 12,
  },
  matchPreviewPressable: {
    marginBottom: 0,
  },
  matchPreviewFooter: {
    marginTop: 16,
    alignItems: "center",
  },
  matchPreviewTabsRow: {
    flexDirection: "row-reverse",
    marginTop: 14,
  },
  matchPreviewHintPill: {
    flexDirection: "row-reverse",
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(255,214,126,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  matchPreviewHintText: {
    color: "#FFDE97",
    fontSize: 11,
    fontWeight: "900",
    marginRight: 7,
  },
  matchDetailShell: {
    flex: 1,
    backgroundColor: "#05070D",
    borderRadius: 23,
    overflow: "hidden",
  },
  matchDetailPageBorderRing: {
    flex: 1,
    padding: 1,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#05070D",
  },
  matchDetailPageBorderSpinner: {
    position: "absolute",
    top: -320,
    right: -320,
    bottom: -320,
    left: -320,
    opacity: 0.92,
  },
  matchDetailPageBorderSpinnerGradient: {
    flex: 1,
  },
  matchDetailTopBar: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 10,
  },
  matchDetailTitleBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 12,
  },
  matchDetailKicker: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    fontWeight: "800",
    fontFamily: MONO_FONT,
  },
  matchDetailTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
  },
  matchDetailContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 128,
    backgroundColor: "#05070D",
  },
  matchDetailShowcaseCard: {
    marginBottom: 8,
    borderRadius: 16,
    backgroundColor: "#05070D",
    borderWidth: 0,
    borderColor: "transparent",
  },
  matchDetailShowcaseBorderRing: {
    borderRadius: 16,
  },
  matchDetailShowcaseShell: {
    paddingBottom: 4,
    backgroundColor: "#05070D",
  },
  matchDetailShowcaseShellSharp: {
    borderRadius: 16,
  },
  matchDetailShowcaseHeaderRow: {
    paddingBottom: 2,
  },
  matchDetailShowcaseBackButton: {
    minWidth: 88,
    height: 32,
    borderRadius: 10,
    paddingHorizontal: 10,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  matchDetailShowcaseBackText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    marginRight: 6,
  },
  matchDetailShowcaseHero: {
    paddingBottom: 8,
  },
  matchDetailShowcaseDivider: {
    height: 0,
    marginHorizontal: 0,
    backgroundColor: "transparent",
  },
  matchDetailShowcaseMetaText: {
    color: "rgba(148,163,184,0.78)",
    fontSize: 9,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 5,
  },
  matchDetailStickyTabsWrap: {
    marginTop: -6,
    paddingBottom: 16,
    paddingHorizontal: 0,
    backgroundColor: "#05070D",
    zIndex: 6,
  },
  matchDetailStickyTabsCard: {
    marginBottom: 0,
    borderRadius: 18,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    overflow: "visible",
  },
  matchDetailStickyTabsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 0,
    backgroundColor: "transparent",
  },
  matchDetailHeroCard: {
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 16,
  },
  matchDetailHeroRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  matchDetailCenterBlock: {
    minWidth: 138,
    alignItems: "center",
    marginHorizontal: 12,
  },
  matchDetailTabsRow: {
    flexDirection: "row-reverse",
    marginTop: 18,
  },
  matchDetailTabButton: {
    minHeight: 58,
    marginLeft: 0,
  },
  matchDetailTabButtonCompact: {
    minHeight: 58,
  },
  matchDetailTabButtonMotion: {
    flex: 1,
  },
  matchDetailTabButtonActive: {
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  matchDetailTabButtonMotionActive: {
    opacity: 1,
  },
  matchDetailTabButtonPressed: {
    opacity: 0.94,
  },
  matchDetailTabIconWrap: {
    marginBottom: 4,
  },
  matchDetailTabButtonText: {
    color: "rgba(148,163,184,0.92)",
    fontSize: 10,
    fontWeight: "900",
    fontFamily: LEAGUE_HEADER_ARABIC_FONT_FAMILY,
    letterSpacing: -0.25,
  },
  matchDetailTabButtonTextCompact: {
    fontSize: 10,
  },
  matchDetailTabButtonTextActive: {
    color: "#FFFFFF",
    textShadowColor: "rgba(255,255,255,0.22)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  detailStatsGrid: {
    flexDirection: "row-reverse",
    marginBottom: 16,
    marginHorizontal: -4,
  },
  detailMetricCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginHorizontal: 4,
  },
  detailMetricValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  detailMetricLabel: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 6,
    textAlign: "center",
  },
  detailSectionHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  detailSectionTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  detailSectionHint: {
    color: "rgba(255,255,255,0.54)",
    fontSize: 10,
    fontWeight: "800",
    fontFamily: MONO_FONT,
  },
  detailPressureCard: {
    paddingHorizontal: 16,
    paddingVertical: 18,
    marginBottom: 16,
  },
  detailPressureBarsRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-end",
    height: 126,
    marginHorizontal: -3,
  },
  detailPressureBarTrack: {
    flex: 1,
    height: "100%",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.04)",
    justifyContent: "flex-end",
    marginHorizontal: 3,
    overflow: "hidden",
  },
  detailPressureBarFill: {
    width: "100%",
    minHeight: 10,
    borderRadius: 999,
  },
  detailSectionTitleStandalone: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
    marginBottom: 12,
  },
  detailHeadToHeadHero: {
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  detailHeadToHeadRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  detailHeadToHeadTeamBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeadToHeadPercentage: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  detailHeadToHeadTeamName: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 6,
  },
  detailHeadToHeadCenter: {
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
  },
  detailHeadToHeadLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  detailHeadToHeadSubLabel: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 4,
  },
  headerPageOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#05070D",
    zIndex: 8,
  },
  headerPageShell: {
    flex: 1,
  },
  headerPageTopRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 8,
  },
  headerPageBackButton: {
    minWidth: 78,
    minHeight: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.05)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  headerPageBackText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    marginLeft: 6,
  },
  headerPageTitleBlock: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 12,
  },
  headerPageKicker: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    fontWeight: "800",
  },
  headerPageTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
  },
  headerPageSummary: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  headerPageIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerPageContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 128,
  },
  headerOverviewCard: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  headerOverviewRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  headerOverviewTextBlock: {
    flex: 1,
    alignItems: "flex-end",
    marginHorizontal: 12,
  },
  headerOverviewTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  headerOverviewSummary: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "right",
    lineHeight: 18,
    marginTop: 6,
  },
  headerOverviewMetricBlock: {
    minWidth: 72,
    alignItems: "center",
  },
  headerOverviewMetricValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  headerOverviewMetricLabel: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 4,
  },
  headerOverviewAccent: {
    width: 4,
    alignSelf: "stretch",
    borderRadius: 999,
  },
  headerTableCard: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  headerTableHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
  },
  headerTableHeaderText: {
    color: "rgba(255,255,255,0.46)",
    fontSize: 10,
    fontWeight: "800",
    minWidth: 48,
    textAlign: "center",
  },
  headerTableHeaderAccent: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
    minWidth: 48,
    textAlign: "center",
  },
  headerTeamHeader: {
    flex: 1,
    textAlign: "right",
  },
  headerTableRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  headerTeamBlock: {
    flex: 1,
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  headerRankBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  headerRankBadgeText: {
    color: "#05070D",
    fontSize: 11,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  headerTeamName: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
  },
  headerClubName: {
    color: "rgba(255,255,255,0.74)",
    fontSize: 12,
    fontWeight: "800",
    minWidth: 72,
    textAlign: "center",
  },
  headerTableValue: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    minWidth: 48,
    textAlign: "center",
  },
  headerTableValueAccent: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    minWidth: 48,
    textAlign: "center",
  },
  glassCard: {
    backgroundColor: "rgba(0,0,0,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 26,
    overflow: "hidden",
    marginBottom: 16,
  },
  matchCard: {
    padding: 0,
    backgroundColor: "rgba(0,0,0,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 26,
    overflow: "hidden",
    marginTop: -6,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 12,
  },
  matchCardFrame: {
    borderRadius: 26,
    padding: 0,
  },
  matchCardInner: {
    borderRadius: 26,
    overflow: "hidden",
    position: "relative",
    padding: 14,
    borderWidth: 0,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  matchCardGlow: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "transparent",
    top: -70,
    left: -44,
    opacity: 0,
  },
  matchCardSheen: {
    position: "absolute",
    top: -18,
    right: -22,
    width: 144,
    height: 96,
    transform: [{ rotate: "12deg" }],
    opacity: 0,
  },
  matchShowcaseBorderRing: {
    borderRadius: 24,
    padding: 0.8,
    overflow: "hidden",
    position: "relative",
  },
  matchShowcaseBorderSpinner: {
    position: "absolute",
    top: -180,
    right: -180,
    bottom: -180,
    left: -180,
    opacity: 0.98,
  },
  matchShowcaseBorderSpinnerGradient: {
    flex: 1,
  },
  matchShowcaseShell: {
    borderRadius: 22,
    overflow: "hidden",
    position: "relative",
    paddingTop: 6,
    paddingBottom: 4,
    backgroundColor: "rgba(5,10,18,0.98)",
  },
  matchShowcaseBackdropOrbPrimary: {
    position: "absolute",
    top: 58,
    left: -22,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(59,130,246,0.12)",
  },
  matchShowcaseBackdropOrbSecondary: {
    position: "absolute",
    top: 128,
    right: -30,
    width: 168,
    height: 168,
    borderRadius: 84,
    backgroundColor: "rgba(234,179,8,0.10)",
  },
  matchShowcaseHeaderActionsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  matchShowcaseUtilityActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  matchShowcaseUtilityButton: {
    width: 31,
    height: 31,
    borderRadius: 10,
    marginLeft: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  matchShowcaseLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgba(239,68,68,0.10)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.22)",
  },
  matchShowcaseLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    marginRight: 5,
    backgroundColor: "#EF4444",
  },
  matchShowcaseLiveBadgeText: {
    color: "#EF4444",
    fontSize: 8,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    letterSpacing: 1,
  },
  matchShowcaseHeroPressable: {
    paddingHorizontal: 12,
    paddingBottom: 4,
    marginTop: -14,
    position: "relative",
    zIndex: 1,
  },
  matchShowcaseContextBlock: {
    alignItems: "center",
    marginTop: -12,
  },
  matchShowcaseCompetitionLogoWrap: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    marginTop: -6,
  },
  matchShowcaseCompetitionLogo: {
    width: 50,
    height: 50,
    transform: [{ scale: 1.24 }],
  },
  matchShowcaseCompetitionLabel: {
    color: "rgba(148,163,184,0.82)",
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  matchShowcaseLeagueName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 0,
  },
  matchShowcaseMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  matchShowcaseMetaText: {
    color: "rgba(148,163,184,0.92)",
    fontSize: 9,
    fontWeight: "700",
    marginLeft: 4,
  },
  matchShowcaseTeamsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: -8,
  },
  matchShowcaseTeamPanel: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 2,
  },
  matchShowcaseTeamArtWrap: {
    width: 66,
    height: 66,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    transform: [{ translateY: 3 }],
  },
  matchShowcaseTeamGlow: {
    position: "absolute",
    width: 44,
    height: 44,
    borderRadius: 22,
    opacity: 0.18,
  },
  matchShowcaseTeamBadge: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(8,15,26,0.92)",
  },
  matchShowcaseTeamLogo: {
    width: 38,
    height: 38,
  },
  matchShowcaseTeamBadgeFallback: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  matchShowcaseTeamBadgeFallbackText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  matchShowcaseTeamName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 6,
  },
  matchShowcaseTeamCaption: {
    color: "rgba(148,163,184,0.70)",
    fontSize: 8,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 6,
  },
  matchShowcaseScoreCenter: {
    width: 104,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  matchShowcaseVersus: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    letterSpacing: 0.8,
    marginHorizontal: 10,
    marginTop: 5,
  },
  matchShowcaseScoreDigitsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  matchShowcaseScoreDigit: {
    color: "#FFFFFF",
    fontSize: 29,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  matchShowcaseScoreDash: {
    color: "rgba(71,85,105,0.92)",
    fontSize: 15,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    marginHorizontal: 7,
    marginTop: 3,
  },
  matchShowcaseCountdownBadge: {
    alignItems: "center",
    marginTop: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.34)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  matchShowcaseCountdownText: {
    color: "#FFDE97",
    fontSize: 14,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  matchShowcaseCountdownCaption: {
    color: "rgba(148,163,184,0.74)",
    fontSize: 7,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 3,
    letterSpacing: 0.3,
  },
  matchShowcaseFooterTabsRow: {
    flexDirection: "row-reverse",
    alignItems: "stretch",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    backgroundColor: "rgba(255,255,255,0.01)",
    position: "relative",
    zIndex: 4,
  },
  matchShowcaseFooterTabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  matchShowcaseFooterTabButtonDivider: {
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(255,255,255,0.08)",
  },
  matchShowcaseFooterTabButtonActive: {
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  matchShowcaseFooterTabIconWrap: {
    minWidth: 28,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 3,
  },
  matchShowcaseFooterAssetIcon: {
    width: 17,
    height: 17,
  },
  matchShowcaseFooterAssetIconLarge: {
    width: 19,
    height: 19,
  },
  matchShowcaseFooterPredictionIcon: {
    width: 26,
    height: 26,
  },
  matchShowcaseFooterTabText: {
    color: "rgba(148,163,184,0.92)",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  matchOpenDetailsArea: {
    position: "relative",
  },
  matchHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 54,
    minHeight: 30,
  },
  matchLeagueName: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  scoreRow: {
    flexDirection: "row-reverse",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 18,
  },
  teamColumn: {
    alignItems: "center",
    width: 68,
    marginHorizontal: 8,
  },
  teamCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  teamCircleText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  teamLogoWrap: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  teamCircleIcon: {
    width: 34,
    height: 34,
  },
  teamColumnTitle: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 7,
    width: "100%",
    textAlign: "center",
  },
  scoreBlock: {
    alignItems: "center",
    minWidth: 128,
    marginHorizontal: 12,
  },
  scoreDigitsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  matchDemoPillWrap: {
    position: "absolute",
    top: 12,
    left: 12,
    zIndex: 3,
  },
  scoreDigit: {
    color: "#FFCC68",
    fontSize: 24,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  scoreDash: {
    color: "rgba(255,212,122,0.72)",
    fontSize: 22,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    marginHorizontal: 7,
  },
  livePill: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "rgba(255,214,126,0.09)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#FF4859",
    marginLeft: 5,
  },
  livePillText: {
    color: "#FFDE97",
    fontSize: 9,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  kickoffCountdownText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    marginTop: 8,
    letterSpacing: 0.4,
  },
  kickoffCountdownCaption: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 4,
  },
  leagueTabsRow: {
    flexDirection: "row-reverse",
    marginTop: 10,
  },
  leagueTabButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 10,
    backgroundColor: "rgba(0,0,0,0.18)",
    borderWidth: 0.8,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  leagueTabButtonContent: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  leagueTabButtonLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#41F17B",
    marginLeft: 6,
    shadowColor: "#41F17B",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 6,
    elevation: 2,
  },
  leagueTabButtonActive: {
    backgroundColor: "rgba(255,214,126,0.14)",
    borderColor: "rgba(255,255,255,0.28)",
  },
  leagueTabButtonText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 10,
    fontWeight: "900",
  },
  leagueTabButtonTextActive: {
    color: "#FFDE97",
  },
  eventCard: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 12,
  },
  eventMinuteBadge: {
    minWidth: 52,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.09)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  eventMinuteText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
  },
  eventTextBlock: {
    flex: 1,
    marginRight: 12,
  },
  eventTextRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  eventSummaryText: {
    flex: 1,
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
  },
  eventMoreText: {
    color: "#63C6FF",
    fontSize: 12,
    fontWeight: "900",
    marginRight: 10,
  },
  modeSwitchButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  modeSwitchButtonActive: {
    backgroundColor: "#F5F9FF",
  },
  modeSwitchButtonText: {
    color: "#8092A6",
    fontSize: 14,
    fontWeight: "800",
  },
  modeSwitchButtonTextActive: {
    color: "#08111B",
  },
  lineupSwitchRow: {
    flexDirection: "row-reverse",
    marginTop: 16,
    marginBottom: 14,
  },
  lineupSummaryCard: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
  },
  lineupSummaryTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  lineupSummaryText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 6,
  },
  lineupStageShell: {
    marginBottom: 14,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#030507",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  lineupStageHeader: {
    position: "relative",
    backgroundColor: "#05070D",
    paddingTop: 18,
    paddingHorizontal: 16,
    paddingBottom: 20,
    overflow: "hidden",
  },
  lineupStageHeaderGlow: {
    position: "absolute",
    top: -18,
    width: 160,
    height: 160,
    borderRadius: 80,
    opacity: 0.18,
  },
  lineupStageHeaderGlowLeft: {
    left: -68,
  },
  lineupStageHeaderGlowRight: {
    right: -68,
  },
  lineupStageBrandWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageBrandImage: {
    width: 84,
    height: 30,
    opacity: 0.92,
  },
  lineupStageHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
  },
  lineupStageHeaderCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
  },
  lineupStageKickoffText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    fontFamily: MONO_FONT,
  },
  lineupStageHeadline: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 8,
  },
  lineupStageTeamBadgeWrap: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageTeamBadgeImage: {
    width: 32,
    height: 32,
  },
  lineupStageTeamFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageTeamFallbackText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  lineupStageFieldWrap: {
    position: "relative",
    backgroundColor: "#040607",
    overflow: "hidden",
  },
  lineupStageFieldShadow: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 26,
    height: 180,
    borderRadius: 48,
    backgroundColor: "rgba(0,0,0,0.36)",
    transform: [{ scaleX: 0.88 }],
  },
  lineupStageFieldPlane: {
    position: "absolute",
    left: 10,
    right: 10,
    top: 96,
    bottom: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageFeatureTabWrap: {
    position: "absolute",
    top: 18,
    left: 20,
    right: 20,
    alignItems: "center",
    zIndex: 4,
  },
  lineupStageFeatureTabPressable: {
    borderRadius: 999,
  },
  lineupStageFeatureTabPressableActive: {
    transform: [{ translateY: 1 }, { scale: 0.985 }],
  },
  lineupStageFeatureTabBorder: {
    minWidth: 168,
    maxWidth: "72%",
    borderRadius: 999,
    padding: 1.25,
    shadowColor: "#9ED5FF",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 7,
  },
  lineupStageFeatureTabBorderActive: {
    shadowOpacity: 0.26,
    shadowRadius: 22,
  },
  lineupStageFeatureTabInner: {
    minHeight: 44,
    borderRadius: 999,
    backgroundColor: "#071018",
    paddingHorizontal: 14,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  lineupStageFeatureTabInnerActive: {
    backgroundColor: "#0B1620",
  },
  lineupStageFeatureTabIconHalo: {
    position: "absolute",
    width: 36,
    height: 36,
    borderRadius: 18,
    right: 12,
    backgroundColor: "#92D6FF",
  },
  lineupStageFeatureTabIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageFeatureTabIconWrapActive: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderColor: "rgba(255,255,255,0.96)",
  },
  lineupStageFeatureTabText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    marginHorizontal: 8,
    letterSpacing: 0.2,
  },
  lineupStageFeatureTabTextActive: {
    color: "#FFFFFF",
  },
  lineupStageFieldSurface: {
    width: "92%",
    height: "100%",
    borderRadius: 26,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.16)",
    overflow: "hidden",
    transform: [{ perspective: 900 }, { rotateX: "58deg" }],
  },
  lineupStageTouchline: {
    position: "absolute",
    left: 14,
    right: 14,
    top: 14,
    bottom: 14,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 14,
  },
  lineupStageHalfwayLine: {
    position: "absolute",
    left: 14,
    right: 14,
    top: "50%",
    height: 2,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  lineupStageCenterCircle: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.18)",
    transform: [{ translateX: -48 }, { translateY: -48 }],
  },
  lineupStageCenterMark: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.28)",
    transform: [{ translateX: -4 }, { translateY: -4 }],
  },
  lineupStageTopBox: {
    position: "absolute",
    left: "24%",
    right: "24%",
    top: 14,
    height: 96,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "rgba(255,255,255,0.18)",
  },
  lineupStageBottomBox: {
    position: "absolute",
    left: "24%",
    right: "24%",
    bottom: 14,
    height: 96,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: "rgba(255,255,255,0.18)",
  },
  lineupStageTopGoalArea: {
    position: "absolute",
    left: "34%",
    right: "34%",
    top: 14,
    height: 42,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "rgba(255,255,255,0.18)",
  },
  lineupStageBottomGoalArea: {
    position: "absolute",
    left: "34%",
    right: "34%",
    bottom: 14,
    height: 42,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: "rgba(255,255,255,0.18)",
  },
  lineupStagePlayerLayer: {
    position: "absolute",
    left: 8,
    right: 8,
    top: 104,
    bottom: 46,
  },
  lineupStagePlacementLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  lineupPlayerMarker: {
    position: "absolute",
    width: 72,
    alignItems: "center",
    zIndex: 2,
  },
  lineupPlayerMarkerSelected: {
    zIndex: 4,
  },
  lineupPlayerPressable: {
    alignItems: "center",
    paddingHorizontal: 6,
    paddingTop: 4,
    paddingBottom: 8,
  },
  lineupPlayerPressableActive: {
    transform: [{ scale: 0.96 }],
  },
  lineupPlayerAvatarShell: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 6,
  },
  lineupPlayerAvatarShellSelected: {
    shadowColor: "#8BD6FF",
    shadowOpacity: 0.34,
    shadowRadius: 16,
    elevation: 9,
  },
  lineupPlayerAvatarCore: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "hidden",
  },
  lineupPlayerAvatarHead: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: "rgba(255,255,255,0.9)",
    marginTop: 5,
  },
  lineupPlayerAvatarBody: {
    width: 34,
    height: 20,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: "rgba(255,255,255,0.22)",
    marginTop: 3,
  },
  lineupPlayerNumberBadge: {
    position: "absolute",
    top: -3,
    left: 8,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
  },
  lineupPlayerNumberBadgeSelected: {
    borderColor: "rgba(99,198,255,0.65)",
  },
  lineupPlayerNumberText: {
    color: "#0A1018",
    fontSize: 10,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  lineupPlayerTeamBadge: {
    position: "absolute",
    top: 0,
    right: 8,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#2FA357",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
  },
  lineupPlayerTeamBadgeSelected: {
    backgroundColor: "#0E6D96",
  },
  lineupPlayerTeamBadgeText: {
    color: "#FFFFFF",
    fontSize: 7,
    fontWeight: "900",
  },
  lineupPlayerName: {
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 5,
    width: "100%",
  },
  lineupPlayerNameSelected: {
    color: "#9EDCFF",
  },
  lineupStageFormationPill: {
    position: "absolute",
    right: 14,
    bottom: 12,
    minWidth: 74,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  lineupStageFormationText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  lineupStageWatermarkWrap: {
    position: "absolute",
    bottom: 18,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  lineupStageWatermarkImage: {
    width: 80,
    height: 28,
    opacity: 0.14,
  },
  lineupVarEditorPanel: {
    paddingTop: 18,
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  lineupVarEditorTopRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  lineupVarEditorActionsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    marginLeft: 10,
  },
  lineupVarEditorActionButton: {
    minHeight: 34,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    marginLeft: 8,
  },
  lineupVarEditorActionButtonPrimary: {
    backgroundColor: "#F5F9FF",
    borderColor: "rgba(255,255,255,0.96)",
  },
  lineupVarEditorActionText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
  },
  lineupVarEditorActionTextPrimary: {
    color: "#08111B",
  },
  lineupVarEditorCopyWrap: {
    flex: 1,
  },
  lineupVarEditorTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  lineupVarEditorHint: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 6,
    lineHeight: 18,
  },
  lineupVarEditorHintSecondary: {
    color: "rgba(158,220,255,0.88)",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 6,
  },
  lineupVarBenchTitle: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
  },
  lineupVarBenchRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    alignItems: "flex-start",
    marginHorizontal: -4,
    paddingTop: 14,
    paddingBottom: 2,
  },
  lineupVarBenchToken: {
    width: 78,
    alignItems: "center",
    marginHorizontal: 4,
    marginBottom: 12,
    paddingTop: 4,
    paddingBottom: 6,
    transform: [{ scale: 1 }],
    zIndex: 4,
  },
  lineupVarBenchTokenSelected: {
    transform: [{ scale: 1.04 }],
  },
  lineupVarBenchTokenPressed: {
    transform: [{ scale: 0.97 }],
  },
  lineupVarBenchAvatarShell: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 5,
  },
  lineupVarBenchAvatarShellSelected: {
    shadowColor: "#8BD6FF",
    shadowOpacity: 0.34,
    shadowRadius: 16,
    elevation: 8,
  },
  lineupVarBenchAvatarCore: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "hidden",
  },
  lineupVarBenchAvatarHead: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
    marginTop: 6,
  },
  lineupVarBenchAvatarBody: {
    width: 36,
    height: 21,
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    backgroundColor: "rgba(255,255,255,0.22)",
    marginTop: 3,
  },
  lineupVarBenchNumberBadge: {
    position: "absolute",
    top: 2,
    left: 12,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
  },
  lineupVarBenchNumberText: {
    color: "#0A1018",
    fontSize: 10,
    fontWeight: "900",
    fontFamily: MONO_FONT,
  },
  lineupVarBenchTeamBadge: {
    position: "absolute",
    top: 5,
    right: 14,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#0E6D96",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.34)",
  },
  lineupVarBenchTeamBadgeText: {
    color: "#FFFFFF",
    fontSize: 7,
    fontWeight: "900",
  },
  lineupVarBenchName: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
    width: "100%",
    marginTop: 8,
  },
  lineupVarBenchEmpty: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 12,
  },
  lineupVarEditorHintWrap: {
    marginTop: 2,
  },
  pitchCard: {
    height: 320,
    borderRadius: 24,
    backgroundColor: "#0C3A1F",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
    position: "relative",
  },
  varXPitchCard: {
    marginTop: 16,
    height: 360,
  },
  pitchCenterLine: {
    position: "absolute",
    left: "50%",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  pitchCenterCircle: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.14)",
    transform: [{ translateX: -42 }, { translateY: -42 }],
  },
  pitchTopBox: {
    position: "absolute",
    left: "23%",
    right: "23%",
    top: 0,
    height: 64,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "rgba(255,255,255,0.14)",
  },
  pitchBottomBox: {
    position: "absolute",
    left: "23%",
    right: "23%",
    bottom: 0,
    height: 64,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: "rgba(255,255,255,0.14)",
  },
  pitchPlayerWrap: {
    position: "absolute",
    transform: [{ translateX: -18 }, { translateY: -18 }],
  },
  pitchPlayerCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.32)",
  },
  pitchPlayerNumber: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  benchWrap: {
    marginTop: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 14,
  },
  benchTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
    marginBottom: 12,
  },
  benchGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  benchPill: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginHorizontal: "1%",
    marginVertical: 4,
  },
  benchPillNumber: {
    color: "#63C6FF",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  benchPillName: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 4,
  },
  pollVotePanel: {
    marginTop: 8,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pollVoteRow: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 38,
  },
  pollVoteDivider: {
    height: 6,
  },
  pollVoteTeamBlock: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 64,
    alignItems: "center",
    justifyContent: "center",
  },
  pollVoteTeamLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
  },
  pollVoteMetricsWrap: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    width: "74%",
    maxWidth: 238,
  },
  pollVoteMetricGroup: {
    alignItems: "center",
    justifyContent: "center",
    width: 64,
  },
  pollVoteMetricLabel: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 11,
    fontWeight: "800",
    marginLeft: 4,
    flexShrink: 0,
  },
  pollVoteMetricValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    flexShrink: 1,
  },
  pollVoteMetricCenterWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  pollVoteMetricCenterText: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },
  pollVoteButton: {
    minWidth: 86,
    width: 86,
    height: 26,
    borderRadius: 999,
    backgroundColor: "#F3F5F8",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  actionButtonContent: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  actionButtonSuccess: {
    backgroundColor: ACTION_SUCCESS_COLOR,
    borderColor: "rgba(65,241,123,0.42)",
  },
  actionButtonSuccessText: {
    color: ACTION_SUCCESS_FOREGROUND,
  },
  actionButtonSuccessIcon: {
    marginRight: 6,
  },
  pollVoteButtonText: {
    color: "#102038",
    fontSize: 11,
    fontWeight: "900",
  },
  predictionsTitleRow: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  predictionsHeaderBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: -4,
    zIndex: 2,
  },
  predictionsHeaderBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  predictionsHeaderBadgeAccent: {
    backgroundColor: "#F8F5FF",
  },
  predictionsHeaderBadgeTrailing: {
    marginLeft: -6,
  },
  predictionsTitleText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
  },
  predictionsBoard: {
    marginTop: 8,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
  },
  predictionsScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  predictionsScorerColumn: {
    width: "48%",
    minWidth: 0,
  },
  predictionsScorerColumnHidden: {
    width: "48%",
  },
  predictionsScoreColumn: {
    flex: 1,
    minWidth: 0,
  },
  predictionsScoreInlineRow: {
    alignItems: "center",
  },
  predictionsScoreInlineRowLeft: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  predictionsScoreInlineRowRight: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  predictionsTeamSideText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },
  predictionsResultText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
    marginHorizontal: 8,
  },
  predictionsVsText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginHorizontal: 12,
  },
  predictionsScoreFieldWrap: {
    width: 50,
    height: 26,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(11,29,53,0.26)",
    alignItems: "center",
    justifyContent: "center",
  },
  predictionsScoreInput: {
    width: "100%",
    height: "100%",
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
  },
  predictionsScorersRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginTop: 14,
  },
  predictionsScorerMetaRow: {
    alignItems: "center",
    width: "100%",
    marginBottom: 10,
  },
  predictionsScorerMetaRowLeft: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  predictionsScorerMetaRowRight: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  predictionsScorerMetaLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
  },
  predictionsScorerTeamChip: {
    minWidth: 108,
    minHeight: 28,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(11,29,53,0.26)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  predictionsScorerTeamChipText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  predictionsScorerTeamChipChevron: {
    marginLeft: 6,
  },
  predictionsScorersCell: {
    width: "100%",
  },
  predictionsScorerSlotWrap: {
    marginTop: 8,
  },
  predictionsPickerWrap: {
    position: "relative",
    width: "100%",
  },
  predictionsPickerWrapOpen: {
    zIndex: 30,
  },
  predictionsPickerTrigger: {
    minHeight: 40,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(11,29,53,0.26)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 12,
  },
  predictionsPickerChevron: {
    marginRight: 6,
  },
  predictionsPickerValueText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
    flex: 1,
  },
  predictionsPickerValuePlaceholder: {
    color: "rgba(255,255,255,0.72)",
  },
  predictionsPickerMenu: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: "100%",
    marginBottom: 6,
    borderRadius: 10,
    backgroundColor: "rgba(12,35,63,0.98)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 12,
  },
  predictionsPickerMenuScroll: {
    maxHeight: 156,
  },
  predictionsPickerOption: {
    flexDirection: "row-reverse",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  predictionsPickerOptionText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
    flex: 1,
  },
  predictionsAvatarFrame: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginLeft: 6,
  },
  predictionsAvatarImage: {
    width: 18,
    height: 18,
  },
  predictionsAvatarFallback: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  predictionsAvatarFallbackText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
  },
  predictionsSaveButton: {
    alignSelf: "center",
    minWidth: 108,
    height: 34,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(17,24,39,0.16)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    marginTop: 10,
  },
  predictionsSaveButtonText: {
    color: "#111111",
    fontSize: 11,
    fontWeight: "900",
  },
  predictionsSaveButtonSaved: {
    backgroundColor: "#FFFFFF",
    borderColor: "rgba(17,24,39,0.22)",
  },
  predictionsScorerHintWrap: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  predictionsScorerHintText: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 16,
  },
  predictionsNoteWrap: {
    marginTop: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  predictionsNoteText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 16,
  },
  pollTweetSection: {
    marginTop: 16,
  },
  pollTweetSectionHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  pollTweetSectionTitleRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  pollTweetSectionLiveDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: "#41F17B",
    marginLeft: 7,
    shadowColor: "#41F17B",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 6,
    elevation: 3,
  },
  pollTweetSectionKicker: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
  },
  pollTweetSectionHint: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 11,
    fontWeight: "800",
    fontFamily: MONO_FONT,
  },
  pollTweetViewport: {
    overflow: "hidden",
    position: "relative",
    backgroundColor: "rgba(2,4,8,0.82)",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  pollTweetTrack: {
    paddingTop: 0,
  },
  pollTweetCard: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.32)",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.08)",
  },
  pollTweetCardHeader: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  pollTweetAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  pollTweetAvatarText: {
    color: "#F7FAFC",
    fontSize: 11,
    fontWeight: "900",
  },
  pollTweetMetaBlock: {
    flex: 1,
    alignItems: "flex-end",
    marginHorizontal: 10,
  },
  pollTweetIdentityRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  pollTweetAuthor: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "right",
  },
  pollTweetHandle: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "right",
    marginRight: 6,
    fontFamily: MONO_FONT,
  },
  pollTweetTimeLabel: {
    color: "rgba(255,255,255,0.42)",
    fontSize: 10,
    fontWeight: "800",
    marginRight: 6,
  },
  pollTweetReplyLine: {
    color: "#2A93F4",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 4,
  },
  pollTweetQuote: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    lineHeight: 20,
    marginTop: 8,
  },
  pollTweetActionsRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  pollTweetActionItem: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  pollTweetActionCount: {
    color: "rgba(255,255,255,0.48)",
    fontSize: 10,
    fontWeight: "800",
    marginRight: 5,
  },
  pollTweetActionIconOnly: {
    width: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  pollTweetFadeTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 28,
  },
  pollTweetFadeBottom: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 28,
  },
  pollCommentComposer: {
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.05)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 14,
    marginTop: 18,
  },
  pollCommentComposerText: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    fontWeight: "800",
    marginRight: 10,
  },
});
