import { Platform, StyleSheet } from "react-native";
import {
  createShadowStyle,
  createTextShadowStyle,
} from "../lib/crossPlatformStyles";

const MONO_FONT = Platform.OS === "ios" ? "Courier" : "monospace";
export const SHELL_WIDTH = 430;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#04070D",
  },
  appRoot: {
    flex: 1,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  blurOrb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.16,
  },
  primaryOrb: {
    width: 260,
    height: 260,
    top: -70,
    right: -40,
  },
  secondaryOrb: {
    position: "absolute",
    width: 300,
    height: 300,
    left: -90,
    bottom: 160,
    borderRadius: 999,
    backgroundColor: "#17325E",
    opacity: 0.12,
  },
  tertiaryOrb: {
    position: "absolute",
    width: 160,
    height: 160,
    right: 30,
    bottom: 260,
    borderRadius: 999,
    backgroundColor: "#421A33",
    opacity: 0.1,
  },
  shell: {
    flex: 1,
    width: "100%",
    maxWidth: SHELL_WIDTH,
    alignSelf: "center",
  },
  noticeWrap: {
    position: "absolute",
    top: 64,
    left: 16,
    right: 16,
    zIndex: 20,
  },
  noticePill: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "rgba(22, 57, 83, 0.74)",
    borderWidth: 1,
    borderColor: "rgba(148,216,255,0.18)",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  noticeText: {
    flex: 1,
    marginRight: 8,
    color: "#E8F6FF",
    textAlign: "right",
    fontSize: 13,
    fontWeight: "700",
  },
  themeSwitchLayer: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    zIndex: 24,
  },
  screenContent: {
    paddingHorizontal: 16,
    paddingTop: 82,
    paddingBottom: 128,
  },
  glassCard: {
    backgroundColor: "rgba(9, 14, 24, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 26,
    overflow: "hidden",
    marginBottom: 16,
  },
  sectionHeader: {
    marginBottom: 18,
  },
  sectionEyebrow: {
    color: "#64B9F8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    textAlign: "right",
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 27,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 8,
  },
  sectionDescription: {
    color: "#8BA0B5",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "right",
    marginTop: 8,
  },
  tiktokCard: {
    marginBottom: 18,
    borderRadius: 30,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tiktokTopRow: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 2,
  },
  tiktokSoundButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.42)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
  },
  tiktokDockWrap: {
    position: "absolute",
    left: 0,
    top: "33%",
    flexDirection: "row",
    alignItems: "center",
    zIndex: 2,
  },
  tiktokVarTab: {
    width: 32,
    height: 108,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(0,0,0,0.84)",
    alignItems: "center",
    justifyContent: "center",
  },
  tiktokVarTabText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    transform: [{ rotate: "90deg" }],
  },
  tiktokDockRail: {
    width: 72,
    marginLeft: 8,
    borderRadius: 8,
    paddingVertical: 12,
    backgroundColor: "rgba(0,0,0,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  tiktokDockButton: {
    alignItems: "center",
    paddingVertical: 8,
  },
  tiktokDockValue: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 6,
  },
  tiktokBottomFade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 220,
  },
  tiktokInfoBlock: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 20,
  },
  tiktokCreatorRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tiktokCreatorText: {
    alignItems: "flex-end",
  },
  tiktokNameRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  tiktokCreatorName: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    marginLeft: 8,
  },
  tiktokHandle: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
  },
  tiktokCreatorBadge: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tiktokCreatorBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  tiktokCaption: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 24,
    textAlign: "right",
    marginTop: 12,
  },
  tiktokTagRow: {
    flexDirection: "row-reverse",
    marginTop: 14,
  },
  tagWrap: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 8,
  },
  tagText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  xDrawerCard: {
    padding: 18,
  },
  drawerTopRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
  },
  drawerChip: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  drawerChipText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  drawerTitleBlock: {
    alignItems: "flex-end",
  },
  drawerKicker: {
    color: "#7CAFD2",
    fontSize: 11,
    fontWeight: "800",
    fontFamily: MONO_FONT,
  },
  drawerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 6,
  },
  drawerChipsRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    marginTop: 14,
    marginHorizontal: -4,
  },
  xSpaceChip: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginHorizontal: 4,
    marginVertical: 4,
  },
  xSpaceChipText: {
    color: "#D8E8F5",
    fontSize: 12,
    fontWeight: "700",
  },
  xHeaderCard: {
    borderRadius: 24,
    overflow: "hidden",
    marginBottom: 16,
  },
  xHeaderGradient: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  xHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  xHeaderTitleBlock: {
    flex: 1,
    alignItems: "flex-end",
    marginHorizontal: 12,
  },
  xHeaderBrand: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    fontFamily: MONO_FONT,
    letterSpacing: 1.8,
  },
  xHeaderSubtitle: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 11,
    fontWeight: "700",
    fontFamily: MONO_FONT,
    marginTop: 4,
    textAlign: "right",
  },
  xAvatarButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  xAvatarCircle: {
    flex: 1,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  xAvatarLetter: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  xComposerButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
  },
  xComposerText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  modeStrip: {
    flexDirection: "row-reverse",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 20,
    padding: 6,
    marginBottom: 16,
  },
  xPostCard: {
    padding: 14,
  },
  xPostRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
  },
  xAvatarTiny: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#102844",
  },
  xAvatarTinyText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  lineupSummaryCard: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
  },
  lineupSummaryTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  lineupSummaryText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 6,
  },
  pitchCard: {
    height: 320,
    borderRadius: 24,
    backgroundColor: "#0C3A1F",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
    position: "relative",
  },
  pitchCenterLine: {
    position: "absolute",
    left: "50%",
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  pitchCenterCircle: {
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.14)",
    transform: [{ translateX: -42 }, { translateY: -42 }],
  },
  pitchTopBox: {
    position: "absolute",
    left: "23%",
    right: "23%",
    top: 0,
    height: 64,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: "rgba(255,255,255,0.14)",
  },
  pitchBottomBox: {
    position: "absolute",
    left: "23%",
    right: "23%",
    bottom: 0,
    height: 64,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: "rgba(255,255,255,0.14)",
  },
  pitchPlayerWrap: {
    position: "absolute",
    transform: [{ translateX: -18 }, { translateY: -18 }],
  },
  pitchPlayerCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.32)",
  },
  pitchPlayerNumber: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  benchWrap: {
    marginTop: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 14,
  },
  benchTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
    marginBottom: 12,
  },
  benchGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  benchPill: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginHorizontal: "1%",
    marginVertical: 4,
  },
  benchPillNumber: {
    color: "#63C6FF",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  benchPillName: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 4,
  },
  pollSummaryRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    marginTop: 18,
  },
  pollMetaBlock: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 18,
    padding: 14,
    marginHorizontal: 4,
    alignItems: "flex-end",
  },
  pollMetaValue: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
  },
  pollMetaLabel: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 6,
  },
  pollRail: {
    height: 18,
    borderRadius: 999,
    overflow: "hidden",
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.06)",
    marginTop: 18,
  },
  pollFillHome: {
    backgroundColor: "#63C6FF",
  },
  pollFillAway: {
    backgroundColor: "#FFB85C",
  },
  pollLabelsRow: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    marginTop: 10,
  },
  pollSideLabel: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  shareBoardButton: {
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  shareBoardButtonText: {
    color: "#07101A",
    fontSize: 14,
    fontWeight: "900",
  },
  bottomDock: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 0,
  },
  studioModalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(1,4,8,0.78)",
  },
  studioModalCard: {
    backgroundColor: "#08131F",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 24,
  },
  studioModalHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  studioModalIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  studioModalHeaderCopy: {
    flex: 1,
    alignItems: "flex-end",
    marginLeft: 12,
  },
  studioModalEyebrow: {
    color: "#8FD6FF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  studioModalTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 6,
  },
  studioPickerButton: {
    marginTop: 18,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: "rgba(24,94,145,0.28)",
    borderWidth: 1,
    borderColor: "rgba(157,218,255,0.22)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  studioPickerButtonText: {
    color: "#EAF8FF",
    fontSize: 14,
    fontWeight: "800",
    marginRight: 8,
  },
  studioPreviewCard: {
    marginTop: 14,
    height: 176,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(157,218,255,0.14)",
    justifyContent: "flex-end",
  },
  studioPreviewPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  studioPreviewPlaceholderText: {
    color: "rgba(255,255,255,0.84)",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 10,
    textAlign: "center",
  },
  studioPreviewCopy: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    alignItems: "flex-end",
  },
  studioPreviewEyebrow: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  studioPreviewTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 5,
  },
  studioAssetBadge: {
    marginTop: 12,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  studioAssetBadgeText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
  },
  studioFieldBlock: {
    marginTop: 16,
  },
  studioFieldLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
    marginBottom: 8,
  },
  studioInput: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.04)",
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    paddingHorizontal: 14,
  },
  studioInputDisabled: {
    opacity: 0.72,
  },
  postComposerCardShell: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "#000000",
    overflow: "hidden",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    ...createShadowStyle({
      color: "#000000",
      x: 0,
      y: 12,
      blur: 22,
      opacity: 0.28,
      elevation: 12,
    }),
  },
  postComposerHeaderBar: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 52,
    paddingRight: 18,
    paddingLeft: 52,
  },
  postComposerHeaderTitle: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
  },
  postComposerHeaderBrandWrap: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  postComposerHeaderBrandText: {
    color: "#FFF7EC",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 0.8,
    ...createTextShadowStyle({
      color: "rgba(0,0,0,0.48)",
      x: 0,
      y: 2,
      blur: 8,
    }),
  },
  postComposerHeaderBrandTag: {
    color: "#6AA5F5",
    fontSize: 14,
    fontWeight: "900",
    marginLeft: 6,
  },
  postComposerCloseButton: {
    position: "absolute",
    top: 16,
    left: 16,
    zIndex: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  postComposerDividerLine: {
    height: 1,
    backgroundColor: "rgba(99,159,224,0.72)",
    marginTop: 1,
    marginHorizontal: -6,
  },
  postComposerIdentityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 18,
  },
  postComposerIdentityCluster: {
    flexDirection: "row",
    alignItems: "center",
  },
  postComposerIdentityNameBlock: {
    alignItems: "flex-end",
    marginRight: 8,
  },
  postComposerIdentityNameRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  postComposerIdentityNameIcon: {
    marginLeft: 6,
    marginRight: 6,
  },
  postComposerIdentityNameValue: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "right",
    flexShrink: 1,
  },
  postComposerIdentityAvatarColumn: {
    alignItems: "center",
    justifyContent: "flex-start",
  },
  postComposerIdentityAvatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  postComposerIdentityAvatarFallback: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0F1720",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  postComposerIdentityAvatarFallbackText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
  },
  postComposerIdentityCompactVar: {
    color: "rgba(255,255,255,0.46)",
    fontSize: 10,
    fontWeight: "800",
    marginRight: 8,
  },
  postComposerIdentityCompactInput: {
    minWidth: 76,
    minHeight: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.02)",
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 8,
    marginRight: 8,
  },
  postComposerTitleRibbon: {
    marginTop: 18,
    alignSelf: "flex-start",
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  postComposerTitleRibbonHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  postComposerTitleRibbonLabel: {
    color: "#FF8B2B",
    fontSize: 10,
    fontWeight: "900",
    marginLeft: 6,
  },
  postComposerTitleRibbonInput: {
    minWidth: 180,
    minHeight: 30,
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "left",
    marginTop: 6,
  },
  postComposerBodyCard: {
    marginTop: 14,
    minHeight: 192,
    position: "relative",
    paddingHorizontal: 0,
    paddingVertical: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  postComposerBodySlashLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  postComposerBodySlash: {
    width: 6,
    height: 28,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.92)",
  },
  postComposerBodySlashHidden: {
    opacity: 0,
  },
  postComposerBodyInput: {
    minHeight: 168,
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 31,
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
  },
  postComposerStatusMessage: {
    marginTop: 10,
    color: "#FFB4B4",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "center",
  },
  postComposerFooterHint: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "right",
    lineHeight: 19,
    marginTop: 12,
  },
  postComposerFooterHintAccent: {
    color: "#FF8B2B",
    fontWeight: "900",
  },
  postComposerActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
  },
  postComposerPrimaryAction: {
    minWidth: 112,
    minHeight: 44,
    borderRadius: 14,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    paddingHorizontal: 14,
  },
  postComposerPrimaryActionDisabled: {
    opacity: 0.42,
  },
  postComposerPrimaryActionText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    marginRight: 8,
  },
  postComposerAttachAction: {
    width: 48,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  postComposerMediaPreviewWrap: {
    marginTop: 12,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    position: "relative",
  },
  postComposerMediaPreview: {
    width: "100%",
    height: 180,
  },
  postComposerMediaRemoveButton: {
    position: "absolute",
    top: 10,
    left: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.56)",
  },
  postComposerActionSpacer: {
    width: 112,
    height: 44,
    opacity: 0,
  },
  postComposerTextarea: {
    minHeight: 132,
    paddingTop: 14,
    paddingBottom: 14,
  },
  postComposerHintText: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 10,
    lineHeight: 20,
  },
  studioFooter: {
    flexDirection: "row-reverse",
    marginTop: 20,
  },
  studioSecondaryButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  studioSecondaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  studioPrimaryButton: {
    flex: 1.3,
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: "#81D4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  studioPrimaryButtonDisabled: {
    opacity: 0.42,
  },
  studioPrimaryButtonText: {
    color: "#04111B",
    fontSize: 14,
    fontWeight: "900",
  },
});
