import { Platform, StyleSheet } from "react-native";
import { X_FEED_COLUMN_WIDTH } from "./x-feed.utils";

export const styles = StyleSheet.create({
  xScreen: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
  },
  xScreenContent: {
    paddingBottom: 120,
    backgroundColor: "#000000",
  },
  xScrollArea: {
    flex: 1,
    backgroundColor: "#000000",
  },
  xCollapsibleHeaderHost: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    backgroundColor: "#000000",
    alignItems: "center",
  },
  xFeedColumn: {
    width: "100%",
    maxWidth: X_FEED_COLUMN_WIDTH,
    alignSelf: "center",
  },
  xFeedColumnInner: {
    width: "100%",
  },
  xWebRefreshIndicator: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    zIndex: 30,
    height: 34,
    borderRadius: 999,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(29,155,240,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  xWebRefreshText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  xHashtagButton: {
    position: "absolute",
    left: 16,
    bottom: 86,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1D9BF0",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    shadowColor: "#1D9BF0",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.32,
    shadowRadius: 18,
    elevation: 8,
  },
  xHashtagButtonText: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    marginTop: -2,
  },
  xComposeFab: {
    position: "absolute",
    backgroundColor: "#1D9BF0",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 40,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    shadowColor: "#1D9BF0",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  xComposeFabPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.96 }],
  },
  xHashtagScreen: {
    flex: 1,
    backgroundColor: "#000000",
  },
  xHashtagHeader: {
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 14,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
  },
  xHashtagHeaderTextBlock: {
    flex: 1,
    paddingHorizontal: 14,
    alignItems: "flex-end",
  },
  xHashtagHeaderTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "right",
  },
  xHashtagHeaderSubtitle: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 4,
    lineHeight: 18,
  },
  xHashtagHeaderBadge: {
    minWidth: 58,
    height: 30,
    borderRadius: 999,
    backgroundColor: "rgba(29,155,240,0.14)",
    borderWidth: 1,
    borderColor: "rgba(29,155,240,0.3)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  xHashtagHeaderBadgeText: {
    color: "#77C8FF",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  xHashtagCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  xHashtagContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 44,
  },
  xHashtagSearchBox: {
    minHeight: 46,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.045)",
    flexDirection: "row-reverse",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  xHashtagSearchInput: {
    flex: 1,
    minHeight: 44,
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  xHashtagSearchArrowButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34,197,94,0.14)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.22)",
  },
  xHashtagCompactList: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.28)",
    backgroundColor: "rgba(5,18,14,0.96)",
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 2,
    marginTop: -2,
    marginBottom: 10,
  },
  xHashtagSearchEmptyText: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  xHashtagVerticalItem: {
    minHeight: 30,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 6,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  xHashtagVerticalLabel: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
  },
  xHashtagVerticalCount: {
    minWidth: 24,
    color: "#86EFAC",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "left",
    marginRight: 10,
  },
  xHashtagHeroCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(29,155,240,0.24)",
    backgroundColor: "rgba(7,15,24,0.96)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    alignItems: "flex-end",
    marginBottom: 14,
  },
  xHashtagHeroEyebrow: {
    color: "#77C8FF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  xHashtagHeroTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 6,
    textAlign: "right",
  },
  xHashtagHeroMeta: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
    textAlign: "right",
  },
  xHashtagEmptyCard: {
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: "flex-end",
  },
  xHashtagEmptyTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "right",
  },
  xHashtagEmptyText: {
    color: "rgba(255,255,255,0.66)",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 22,
    textAlign: "right",
    marginTop: 8,
  },
  xComposerTool: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
  },
  xEmptyStateCard: {
    marginTop: 18,
    marginHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    alignItems: "flex-end",
  },
  xEmptyStateTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  xEmptyStateText: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 21,
    textAlign: "right",
    marginTop: 6,
  },
  xLoadMoreState: {
    paddingVertical: 18,
    alignItems: "center",
  },
  xLoadMoreStateText: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 13,
    fontWeight: "700",
  },
  xAvatarTiny: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1A8CD8",
  },
  xAvatarTinyImage: {
    width: "100%",
    height: "100%",
  },
  xAvatarTinyText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  xPrivateThreadHeader: {
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "#000000",
  },
  xPrivateThreadHeaderIdentity: {
    flexDirection: "row-reverse",
    alignItems: "center",
    flex: 1,
    marginLeft: 12,
  },
  xPrivateThreadHeaderTextBlock: {
    flex: 1,
    marginRight: 12,
    alignItems: "flex-end",
  },
  xPrivateThreadHeaderTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  xPrivateThreadHeaderHandle: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 3,
  },
  xPrivateThreadContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 100,
  },
  xPrivateThreadEmptyCard: {
    marginTop: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 18,
    paddingVertical: 18,
    alignItems: "flex-end",
  },
  xPrivateThreadEmptyTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "right",
  },
  xPrivateThreadEmptyText: {
    color: "rgba(255,255,255,0.66)",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 22,
    textAlign: "right",
    marginTop: 8,
  },
  xPrivateMessageBubbleWrap: {
    width: "100%",
    marginBottom: 10,
  },
  xPrivateMessageBubbleWrapMe: {
    alignItems: "flex-start",
  },
  xPrivateMessageBubbleWrapPeer: {
    alignItems: "flex-end",
  },
  xPrivateMessageBubble: {
    maxWidth: "78%",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
  },
  xPrivateMessageBubbleMe: {
    backgroundColor: "#1D9BF0",
    borderTopLeftRadius: 8,
  },
  xPrivateMessageBubblePeer: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderTopRightRadius: 8,
  },
  xPrivateMessageBubbleText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 22,
    textAlign: "right",
  },
  xPrivateMessageBubbleTime: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 8,
  },
  xPrivateThreadComposer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row-reverse",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "#000000",
  },
  xPrivateThreadInput: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.05)",
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
    paddingHorizontal: 14,
  },
  xPrivateThreadSendButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#1D9BF0",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  xPrivateThreadSendButtonDisabled: {
    opacity: 0.45,
  },
  xDetailScreen: {
    flex: 1,
    width: "100%",
    backgroundColor: "#000000",
    ...(Platform.OS === "web"
      ? {
          minHeight: "100%",
          height: "100%",
        }
      : null),
  },
  xPostDetailOverlay: {
    ...(Platform.OS === "web"
      ? {
          position: "fixed",
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
          width: "100%",
          height: "100%",
        }
      : StyleSheet.absoluteFillObject),
    zIndex: 250,
    elevation: 250,
    backgroundColor: "#000000",
  },
  xDetailHeader: {
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
  },
  xDetailCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  xDetailHeaderTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
  },
  xDetailHeaderSpacer: {
    width: 34,
    height: 34,
  },
  xDetailScrollArea: {
    flex: 1,
    backgroundColor: "#000000",
  },
  xDetailContent: {
    paddingBottom: 40,
    backgroundColor: "#000000",
  },
  xDetailRepliesSection: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
  },
  xDetailRepliesTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  xReplyScreenContent: {
    paddingBottom: 36,
  },
  xReplyComposerScreen: {
    flex: 1,
    backgroundColor: "#000000",
  },
  xReplyComposerTopBar: {
    paddingTop: 16,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 4,
    alignItems: "flex-start",
    backgroundColor: "#000000",
  },
  xReplyComposerCancelButton: {
    minHeight: 30,
    paddingHorizontal: 16,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  xReplyComposerCancelButtonText: {
    color: "#05080F",
    fontSize: 13,
    fontWeight: "900",
  },
  xReplyComposerCard: {
    backgroundColor: "#000000",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 28,
  },
  xReplyComposerIdentityRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  xReplyComposerAvatarWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#12364A",
  },
  xReplyComposerAvatarImage: {
    width: "100%",
    height: "100%",
  },
  xReplyComposerAvatarFallbackText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  xReplyComposerIdentityText: {
    flex: 1,
    marginRight: 12,
    alignItems: "flex-end",
  },
  xReplyComposerIdentityName: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
  },
  xReplyComposerIdentityVarId: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 3,
    letterSpacing: 0.8,
  },
  xReplyComposerBrandWrap: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
  },
  xReplyComposerBrandText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  xReplyComposerBrandAccent: {
    color: "#0F97A7",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.6,
    marginLeft: 3,
    marginTop: 3,
  },
  xReplyComposerInputCard: {
    minHeight: 184,
    paddingTop: 20,
    paddingBottom: 16,
    justifyContent: "space-between",
  },
  xReplyComposerInput: {
    minHeight: 124,
    alignSelf: "stretch",
    color: "#FFFFFF",
    fontSize: 21,
    fontWeight: "800",
    lineHeight: 30,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  xReplyComposerSlashLayer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 62,
    alignItems: "center",
  },
  xReplyComposerSlash: {
    width: 7,
    height: 22,
    borderRadius: 4,
    backgroundColor: "#F4FAFF",
  },
  xReplyComposerSlashHidden: {
    opacity: 0.12,
  },
  xReplyComposerActionsRow: {
    minHeight: 34,
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  xReplyComposerSendAction: {
    position: "absolute",
    left: 0,
    minHeight: 28,
    borderRadius: 999,
    borderWidth: 1.2,
    borderColor: "rgba(15,151,167,0.9)",
    paddingLeft: 10,
    paddingRight: 12,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.88)",
  },
  xReplyComposerAttachAction: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  xReplyComposerSendLabel: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
    marginLeft: 6,
    marginBottom: 1,
  },
});
