import { createCompatStyleSheet } from "../../lib/crossPlatformStyles";

export const styles = createCompatStyleSheet({
  root: {
    flex: 1,
    backgroundColor: "#000000",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 58,
    paddingBottom: 40,
    gap: 18,
  },
  headerRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerCopy: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 10,
  },
  headerEyebrow: {
    color: "rgba(244,197,101,0.78)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 4,
    textAlign: "center",
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
    textAlign: "center",
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  headerSpacer: {
    width: 42,
    height: 42,
  },
  identityBanner: {
    minHeight: 0,
    borderRadius: 26,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
    backgroundColor: "#000000",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 12,
  },
  identityAccentGlow: {
    position: "absolute",
    top: -56,
    left: -30,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "transparent",
  },
  identityHeaderLine: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 13,
  },
  avatarRing: {
    width: 76,
    height: 76,
    borderRadius: 38,
    padding: 4,
    backgroundColor: "rgba(244,197,101,0.95)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 34,
  },
  identityCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  identityNameRow: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 7,
  },
  identityName: {
    color: "#FFFFFF",
    flex: 1,
    minWidth: 0,
    fontSize: 23,
    fontWeight: "900",
    textAlign: "right",
  },
  identityInfoRow: {
    alignItems: "flex-end",
    marginTop: 8,
    gap: 5,
  },
  identityAssociation: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
    maxWidth: "100%",
  },
  identityVarIdText: {
    color: "#F4C565",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "right",
    letterSpacing: 0.3,
  },
  identityRewardsTracker: {
    marginTop: 14,
    width: "100%",
  },
  profileMetricGroupsGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 10,
  },
  profileMetricGroupCard: {
    width: "48%",
    minWidth: 150,
    flexGrow: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  profileMetricGroupHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  profileMetricGroupIcon: {
    width: 34,
    height: 34,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  profileMetricGroupTitle: {
    flex: 1,
    minWidth: 0,
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
  },
  profileMetricGroupBody: {
    gap: 8,
  },
  profileMetricCell: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  profileMetricCellValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "left",
  },
  profileMetricCellLabel: {
    flex: 1,
    minWidth: 0,
    color: "rgba(255,255,255,0.66)",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  followedPreviewSection: {
    gap: 12,
    borderRadius: 20,
    padding: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(52,211,153,0.20)",
  },
  followedPreviewHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 10,
  },
  followedPreviewIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(52,211,153,0.14)",
    borderWidth: 1,
    borderColor: "rgba(52,211,153,0.24)",
  },
  followedPreviewHeaderCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  followedPreviewTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
  },
  followedPreviewHint: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "right",
  },
  followedPreviewList: {
    gap: 8,
  },
  followedPreviewCard: {
    minHeight: 54,
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 10,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 9,
    backgroundColor: "rgba(0,0,0,0.26)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  followedPreviewAvatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(29,155,240,0.82)",
  },
  followedPreviewAvatarImage: {
    width: "100%",
    height: "100%",
  },
  followedPreviewAvatarFallback: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  followedPreviewCardCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  followedPreviewName: {
    maxWidth: "100%",
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "right",
  },
  followedPreviewVarId: {
    maxWidth: "100%",
    color: "rgba(255,255,255,0.56)",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 3,
    textAlign: "right",
  },
  followedPreviewEmptyCard: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "rgba(0,0,0,0.22)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  followedPreviewEmptyText: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 20,
    textAlign: "right",
  },
  showcaseSection: {
    gap: 14,
  },
  showcaseHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  showcaseHeaderCopy: {
    flex: 1,
    alignItems: "flex-end",
  },
  showcaseTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "right",
  },
  showcaseHint: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "right",
    marginTop: 4,
  },
  showcaseBadge: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,197,101,0.14)",
    borderWidth: 1,
    borderColor: "rgba(244,197,101,0.28)",
  },
  predictionsList: {
    gap: 12,
  },
  predictionCardOuter: {
    borderRadius: 22,
    padding: 1,
  },
  predictionCardInner: {
    borderRadius: 21,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#070B12",
    gap: 12,
  },
  predictionTopRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  competitionChip: {
    flex: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  competitionChipText: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "900",
  },
  predictionHeroBlock: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  predictionHeroLabel: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 6,
  },
  predictionHeroValue: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 1,
    textAlign: "center",
  },
  predictionTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
    lineHeight: 22,
  },
  predictionFooter: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  predictionFooterItem: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 6,
  },
  predictionFooterText: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 11,
    fontWeight: "700",
  },
  predictionPointsBadge: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(65,241,123,0.12)",
    borderWidth: 1,
    borderColor: "rgba(65,241,123,0.28)",
  },
  predictionPointsBadgePending: {
    backgroundColor: "rgba(244,197,101,0.12)",
    borderColor: "rgba(244,197,101,0.28)",
  },
  predictionPointsBadgeNeutral: {
    backgroundColor: "rgba(29,161,242,0.12)",
    borderColor: "rgba(29,161,242,0.28)",
  },
  predictionPointsText: {
    fontSize: 14,
    fontWeight: "900",
  },
  emptyShowcaseCard: {
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 28,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
    gap: 10,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,197,101,0.12)",
    borderWidth: 1,
    borderColor: "rgba(244,197,101,0.24)",
    marginBottom: 4,
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  emptyText: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 13,
    lineHeight: 22,
    textAlign: "center",
  },
  emptyCtaRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(29,161,242,0.14)",
    borderWidth: 1,
    borderColor: "rgba(29,161,242,0.28)",
  },
  emptyCtaText: {
    color: "#8BD6FF",
    fontSize: 12,
    fontWeight: "900",
  },
});
