import { StyleSheet } from "react-native";
import { createCompatStyleSheet } from "../../lib/crossPlatformStyles";
import {
  SLIDE_HORIZONTAL_PADDING,
  SLIDE_THUMB_SIZE,
} from "./profile.constants";

export const styles = createCompatStyleSheet({
  profileRoot: {
    flex: 1,
  },
  profileBackgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  profileGlowOrb: {
    position: "absolute",
    top: -30,
    right: -40,
    width: 240,
    height: 240,
    borderRadius: 999,
    backgroundColor: "rgba(244,197,101,0.14)",
  },
  profileGlowOrbSecondary: {
    position: "absolute",
    bottom: 120,
    left: -50,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(51,136,255,0.10)",
  },
  profileScroll: {
    flex: 1,
  },
  profileContent: {
    paddingHorizontal: 16,
    paddingTop: 82,
    paddingBottom: 110,
  },
  headerCopy: {
    alignItems: "flex-end",
  },
  headerEyebrow: {
    color: "rgba(244,197,101,0.72)",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    textAlign: "right",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 6,
  },
  idCardShadow: {
    marginTop: 8,
    alignSelf: "center",
  },
  idCardFrame: {
    overflow: "hidden",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 12,
  },
  idCardSurface: {
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: "transparent",
  },
  idCardGlow: {
    position: "absolute",
    top: -24,
    left: -18,
    width: 148,
    height: 148,
    borderRadius: 74,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  idCardGlowSecondary: {
    position: "absolute",
    bottom: -92,
    right: -36,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: "rgba(15,118,110,0.20)",
  },
  idCardWatermark: {
    position: "absolute",
    top: 18,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.06,
  },
  idCardWatermarkImage: {
    width: 264,
    height: 196,
    transform: [{ translateX: 16 }, { translateY: 10 }],
  },
  idCardBadgeRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  idCardBadge: {
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  idCardBadgeText: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 11,
    fontWeight: "900",
    marginRight: 6,
    letterSpacing: 0.6,
  },
  idCardStatusPill: {
    flexDirection: "row-reverse",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  idCardStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#34D399",
  },
  idCardStatusText: {
    marginRight: 8,
    color: "rgba(255,255,255,0.78)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  idTopBand: {
    minHeight: 74,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  idTopBandBlockLeft: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
  },
  idTopBandBlockRight: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  idTopBandBlockRightNarrow: {
    flex: 1.14,
    minWidth: 0,
    alignItems: "flex-end",
  },
  idTopBandOverline: {
    color: "rgba(45,110,71,0.72)",
    fontSize: 9,
    fontWeight: "800",
    textAlign: "right",
    marginBottom: 2,
  },
  idTopBandTitle: {
    color: "#2D6E47",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "right",
    lineHeight: 18,
    flexShrink: 1,
  },
  idTopBandTitleRightNarrow: {
    fontSize: 11,
    lineHeight: 15,
  },
  idTopBandTitleLeft: {
    textAlign: "left",
  },
  idTopBandSubtitle: {
    color: "rgba(45,110,71,0.82)",
    fontSize: 9,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 2,
    flexShrink: 1,
  },
  idTopBandSubtitleLeft: {
    textAlign: "left",
  },
  idTopBandSeal: {
    width: 90,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 6,
  },
  idTopBandSealImage: {
    width: 88,
    height: 62,
  },
  idTopBandSealText: {
    color: "#2D6E47",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  saudiPalmLeafRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  saudiPalmLeafRowMid: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    marginTop: 2,
  },
  saudiPalmLeaf: {
    width: 14,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#2D6E47",
  },
  saudiPalmLeafWide: {
    width: 18,
  },
  saudiPalmLeafCenter: {
    width: 16,
  },
  saudiPalmTrunk: {
    width: 4,
    height: 15,
    borderRadius: 999,
    backgroundColor: "#2D6E47",
    marginTop: 2,
  },
  saudiSwordWrap: {
    position: "absolute",
    bottom: 10,
    width: 44,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  saudiSword: {
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
  },
  saudiSwordLeft: {
    transform: [{ rotate: "26deg" }],
  },
  saudiSwordRight: {
    transform: [{ rotate: "-26deg" }],
  },
  saudiSwordBlade: {
    width: 18,
    height: 2.5,
    borderRadius: 999,
    backgroundColor: "#2D6E47",
  },
  saudiSwordHandle: {
    width: 4,
    height: 6,
    borderRadius: 2,
    backgroundColor: "#2D6E47",
    marginLeft: 2,
  },
  idNameBand: {
    alignItems: "flex-end",
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 0,
  },
  idNameBandNarrow: {
    paddingTop: 18,
    paddingBottom: 0,
  },
  idArabicPrimaryName: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "right",
    lineHeight: 28,
  },
  idEnglishProfileName: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 5,
    letterSpacing: 0.3,
  },
  idCardBody: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
  },
  idPortraitColumn: {
    width: 88,
    alignItems: "center",
  },
  idPortraitColumnNarrow: {
    width: 78,
    marginTop: 0,
    marginLeft: 0,
  },
  portraitFrame: {
    width: 70,
    height: 92,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  portraitFrameCompact: {
    width: 40,
    height: 52,
    borderRadius: 8,
    borderWidth: 1,
  },
  portraitImage: {
    width: "100%",
    height: "100%",
  },
  idEnglishBadge: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.9,
    marginTop: 7,
  },
  idEnglishName: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 4,
  },
  idCenterColumn: {
    paddingTop: 2,
    alignItems: "center",
    position: "absolute",
    right: 20,
    top: 4,
  },
  idCenterColumnNarrow: {
    left: 0,
    right: 0,
    top: -5,
    alignItems: "center",
    opacity: 0.6,
  },
  idCompactPortraitScaleWrap: {
    transform: [{ scale: 0.8 }],
  },
  idDetailsColumn: {
    flex: 1,
    marginLeft: 18,
    minHeight: 0,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "flex-start",
  },
  idDetailsColumnNarrow: {
    minHeight: 0,
    marginLeft: 12,
    marginTop: 0,
    paddingTop: 12,
    paddingBottom: 8,
    justifyContent: "flex-start",
  },
  idEnglishInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  idEnglishInfoLabel: {
    color: "rgba(45,90,58,0.66)",
    fontSize: 9,
    fontWeight: "900",
    marginRight: 6,
  },
  idEnglishInfoValue: {
    color: "#14301B",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 13,
    flex: 1,
  },
  idArabicColumn: {
    flex: 1,
    alignItems: "flex-end",
    minWidth: 128,
    paddingTop: 6,
    paddingLeft: 2,
  },
  idPairedInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  idPairedInfoRowNarrow: {
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  idPairedInfoEnglishBlock: {
    flex: 0.96,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    marginRight: 4,
  },
  idPairedInfoEnglishBlockNarrow: {
    flex: 1.08,
    marginRight: 0,
    marginTop: 0,
    transform: [{ translateX: -8 }],
  },
  idPairedInfoEnglishLabel: {
    color: "rgba(255,255,255,0.54)",
    fontSize: 10,
    fontWeight: "900",
    marginRight: 4,
    letterSpacing: 0.1,
  },
  idPairedInfoEnglishLabelCompact: {
    fontSize: 8,
    marginRight: 3,
    letterSpacing: 0,
  },
  idPairedInfoEnglishLabelIdRow: {
    fontSize: 9,
  },
  idPairedInfoEnglishValue: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 14,
  },
  idPairedInfoEnglishValueEmphasis: {
    fontSize: 10,
    lineHeight: 14,
  },
  idPairedInfoEnglishValueIdRow: {
    fontSize: 10,
    lineHeight: 14,
  },
  idPairedInfoEnglishValueNarrow: {
    flexShrink: 1,
    fontSize: 10,
    lineHeight: 14,
  },
  idPairedInfoEnglishValueTight: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minWidth: 0,
    textAlign: "left",
  },
  idPairedInfoArabicValueTight: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    minWidth: 0,
    textAlign: "right",
  },
  idPairedInfoArabicBlock: {
    flex: 1.04,
    flexDirection: "row-reverse",
    alignItems: "center",
    minWidth: 0,
  },
  idPairedInfoArabicBlockNarrow: {
    flex: 0.95,
    marginRight: 0,
  },
  idPairedInfoArabicLabel: {
    color: "rgba(255,255,255,0.54)",
    fontSize: 8,
    fontWeight: "800",
    textAlign: "right",
    marginLeft: 4,
    flexShrink: 0,
  },
  idPairedInfoArabicLabelIdRow: {
    fontSize: 9,
  },
  idPairedInfoArabicValue: {
    color: "#FFFFFF",
    flex: 1,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "right",
    lineHeight: 14,
  },
  idPairedInfoArabicValueEmphasis: {
    fontSize: 10,
    lineHeight: 14,
  },
  idPairedInfoArabicValueIdRow: {
    fontSize: 10,
    lineHeight: 14,
  },
  idPairedInfoArabicValueNarrow: {
    flexShrink: 1,
  },
  identityBilingualInfoRow: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(57,113,73,0.12)",
    paddingBottom: 8,
    marginBottom: 8,
  },
  identityBilingualInfoRowCompact: {
    flex: 1,
    borderBottomWidth: 0,
    marginBottom: 0,
    paddingBottom: 0,
  },
  identityBilingualInfoHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  identityBilingualInfoLabelArabic: {
    color: "#315A3C",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "right",
  },
  identityBilingualInfoLabelEnglish: {
    color: "rgba(45,90,58,0.64)",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  identityBilingualInfoValues: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginTop: 4,
  },
  identityBilingualInfoValueArabic: {
    color: "#14301B",
    flex: 1,
    fontSize: 11,
    fontWeight: "900",
    textAlign: "right",
    lineHeight: 16,
    marginLeft: 10,
  },
  identityBilingualInfoValueEnglish: {
    color: "#14301B",
    flex: 1,
    fontSize: 10,
    fontWeight: "800",
    textAlign: "left",
    lineHeight: 15,
  },
  idArabicHeaderRow: {
    width: "100%",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  idMiniPortraitWrap: {
    marginLeft: 8,
  },
  idArabicName: {
    color: "#102F18",
    flex: 1,
    fontSize: 10,
    fontWeight: "900",
    textAlign: "right",
    marginBottom: 0,
    lineHeight: 15,
  },
  identityArabicInfoRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 10,
  },
  identityArabicInfoLabel: {
    color: "#315A3C",
    fontSize: 9,
    fontWeight: "800",
    textAlign: "right",
    marginLeft: 8,
    minWidth: 88,
  },
  identityArabicInfoValue: {
    color: "#14301B",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "right",
    flex: 1,
    lineHeight: 14,
  },
  idCardFooter: {
    minHeight: 44,
    borderTopWidth: 1,
    borderTopColor: "rgba(57,113,73,0.14)",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  idFooterTitle: {
    color: "#1C4126",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "right",
  },
  idFooterMeta: {
    color: "rgba(28,65,38,0.72)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  barcodeWrap: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: 21,
    width: 70,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.08)",
    marginTop: 7,
    alignSelf: "center",
    justifyContent: "center",
  },
  barcodeBar: {
    height: "100%",
    marginRight: 1,
  },
  idBarcodeValue: {
    color: "rgba(255,255,255,0.76)",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.7,
    marginTop: 3,
  },
  gestureHintPanel: {
    marginTop: 12,
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  gestureHintText: {
    flex: 1,
    color: "rgba(255,255,255,0.82)",
    fontSize: 12,
    lineHeight: 24,
    fontWeight: "700",
    textAlign: "right",
    marginRight: 10,
  },
  slidersStack: {
    marginTop: 18,
    gap: 12,
  },
  adminConsoleCard: {
    marginTop: 18,
    gap: 10,
  },
  adminConsoleHeaderRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  adminConsoleBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "rgba(244,197,101,0.16)",
    borderWidth: 1,
    borderColor: "rgba(244,197,101,0.34)",
  },
  adminConsoleBadgeText: {
    color: "#F4C565",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  adminConsoleVarId: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "800",
  },
  adminConsoleButton: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(99,198,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(99,198,255,0.20)",
  },
  adminConsoleCopy: {
    flex: 1,
    alignItems: "flex-end",
    marginLeft: 14,
  },
  adminConsoleEyebrow: {
    color: "rgba(99,198,255,0.82)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textAlign: "right",
  },
  adminConsoleTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "right",
    marginTop: 4,
  },
  adminConsoleHint: {
    color: "rgba(255,255,255,0.70)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 20,
    textAlign: "right",
    marginTop: 6,
  },
  adminConsoleIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#63C6FF",
  },
  adminConsoleSecondaryButton: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  adminConsoleSecondaryText: {
    color: "#D7E6FF",
    fontSize: 13,
    fontWeight: "800",
  },
  sliderTrack: {
    height: 62,
    borderRadius: 22,
    overflow: "hidden",
    justifyContent: "center",
    backgroundColor: "rgba(8,14,24,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  sliderTextRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 108,
  },
  sliderText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    marginRight: 8,
    lineHeight: 18,
  },
  sliderTrailIcons: {
    position: "absolute",
    right: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  sliderTrailIconSpacing: {
    marginLeft: -4,
  },
  sliderThumb: {
    position: "absolute",
    left: SLIDE_HORIZONTAL_PADDING,
    top: SLIDE_HORIZONTAL_PADDING,
    width: SLIDE_THUMB_SIZE,
    height: 46,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.95)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 10,
  },
  sliderThumbCompleted: {
    backgroundColor: "#FFFFFF",
  },
  messageText: {
    color: "#F4C565",
    fontSize: 13,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 16,
  },
  modalRoot: {
    flex: 1,
    backgroundColor: "#03060E",
  },
  modalContent: {
    paddingHorizontal: 18,
    paddingTop: 64,
    paddingBottom: 42,
  },
  modalHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  modalHeaderCopy: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 12,
  },
  modalEyebrow: {
    color: "rgba(244,197,101,0.72)",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 5,
    textAlign: "center",
  },
  modalIconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  modalPrimaryButton: {
    minWidth: 68,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    backgroundColor: "#F4C565",
  },
  modalPrimaryButtonText: {
    color: "#09111C",
    fontSize: 14,
    fontWeight: "900",
  },
  modalHeaderSpacer: {
    minWidth: 68,
    height: 44,
  },
  previewHeroCard: {
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    alignItems: "center",
  },
  previewPortraitRing: {
    width: 112,
    height: 112,
    borderRadius: 56,
    padding: 3,
    backgroundColor: "rgba(244,197,101,0.18)",
  },
  previewPortraitImage: {
    width: "100%",
    height: "100%",
    borderRadius: 53,
  },
  previewIdentityCopy: {
    alignItems: "center",
    marginTop: 16,
  },
  previewNameRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 6,
  },
  previewName: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
  },
  previewHandle: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 6,
  },
  previewBio: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    marginTop: 10,
  },
  previewStatsGrid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 16,
    gap: 12,
  },
  previewStatCard: {
    width: "48%",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  previewStatValue: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "right",
  },
  previewStatLabel: {
    color: "rgba(255,255,255,0.70)",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    marginTop: 8,
  },
  previewDetailsCard: {
    marginTop: 16,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  previewPredictionsCard: {
    marginTop: 16,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  previewPredictionsTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "right",
    marginBottom: 12,
  },
  previewPredictionRow: {
    flexDirection: "row-reverse",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  previewPredictionCopyColumn: {
    flex: 1,
    alignItems: "flex-end",
    marginLeft: 14,
  },
  previewPredictionMetaColumn: {
    minWidth: 74,
    alignItems: "flex-start",
  },
  previewPredictionTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "right",
  },
  previewPredictionMeta: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 6,
  },
  previewPredictionPoints: {
    color: "#F4C565",
    fontSize: 14,
    fontWeight: "900",
  },
  previewPredictionLockedAt: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 6,
    textAlign: "left",
  },
  previewPredictionsEmpty: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
  },
  previewDetailRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  previewDetailLabel: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  previewDetailValue: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "left",
    marginRight: 18,
  },
  editPanel: {
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  editAvatarSection: {
    marginBottom: 16,
  },
  editAvatarCard: {
    borderRadius: 18,
    padding: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    alignItems: "center",
  },
  editAvatarPreviewWrap: {
    width: 112,
    height: 112,
    borderRadius: 56,
    padding: 3,
    backgroundColor: "rgba(244,197,101,0.18)",
  },
  editAvatarPreview: {
    width: "100%",
    height: "100%",
    borderRadius: 53,
  },
  editAvatarCopy: {
    alignItems: "center",
    marginTop: 12,
    marginBottom: 14,
  },
  editAvatarTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  editAvatarHint: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 6,
  },
  editAvatarButton: {
    minHeight: 44,
    borderRadius: 14,
    paddingHorizontal: 16,
    backgroundColor: "#F4C565",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  editAvatarButtonText: {
    color: "#09111C",
    fontSize: 13,
    fontWeight: "900",
    marginRight: 8,
  },
  fieldGroup: {
    marginBottom: 14,
  },
  fieldLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
    marginBottom: 8,
  },
  fieldInput: {
    minHeight: 52,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  fieldInputMultiline: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  editInfoNote: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 4,
  },
  associationOptionsRow: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    gap: 8,
  },
  associationOption: {
    minWidth: 88,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
  },
  associationOptionActive: {
    borderColor: "rgba(244,197,101,0.72)",
    backgroundColor: "rgba(244,197,101,0.14)",
  },
  associationOptionText: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 13,
    fontWeight: "800",
  },
  associationOptionTextActive: {
    color: "#F4C565",
  },
  cardConnectPanel: {
    marginTop: 14,
    gap: 8,
    alignSelf: "stretch",
    width: "100%",
    maxWidth: "100%",
  },
  cardConnectShareButton: {
    flexDirection: "row-reverse",
    alignItems: "center",
    alignSelf: "stretch",
    width: "100%",
    maxWidth: "100%",
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  cardConnectShareButtonPressed: {
    opacity: 0.88,
  },
  cardConnectShareIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F5F8",
    marginLeft: 8,
    flexShrink: 0,
  },
  cardConnectShareText: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  cardConnectSearchRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    alignSelf: "stretch",
    width: "100%",
    maxWidth: "100%",
    gap: 8,
  },
  cardConnectSearchInput: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  cardConnectCameraButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    flexShrink: 0,
  },
  cardConnectCameraButtonPressed: {
    opacity: 0.88,
  },
  cardConnectFeedbackText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    lineHeight: 18,
  },
});
