create extension if not exists pgcrypto;

alter table public.users
  add column if not exists username text;

alter table public.users
  add column if not exists bio text;

alter table public.users
  add column if not exists phone text;

alter table public.users
  add column if not exists location text;

alter table public.users
  add column if not exists avatar_url text;

alter table public.users
  add column if not exists avatar_frame_enabled boolean not null default false;

alter table public.users
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.user_profile_preferences (
  user_id uuid primary key references public.users (id) on delete cascade,
  background_image text not null default '',
  layout_order jsonb not null default '["hero","comments-outline","likes-follow","likes-blue","comments-green","share-amber","likes-red","repost-cyan"]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_aliases (
  id integer generated by default as identity primary key,
  user_id uuid not null references public.users (id) on delete cascade,
  alias_type text not null check (alias_type in ('display_name', 'handle')),
  alias_value text not null,
  created_at timestamptz not null default now(),
  unique (user_id, alias_type, alias_value)
);

create index if not exists user_aliases_user_id_idx
  on public.user_aliases (user_id);

create table if not exists public.user_follows (
  id integer generated by default as identity primary key,
  follower_id uuid not null references public.users (id) on delete cascade,
  following_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create index if not exists user_follows_follower_id_idx
  on public.user_follows (follower_id);

create index if not exists user_follows_following_id_idx
  on public.user_follows (following_id);

create table if not exists public.x_posts (
  id integer generated by default as identity primary key,
  author_id uuid not null references public.users (id) on delete cascade,
  author_name text not null,
  author_handle text not null,
  content text not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists x_posts_author_id_idx
  on public.x_posts (author_id, created_at desc);

create table if not exists public.x_post_comments (
  id integer generated by default as identity primary key,
  post_id integer not null references public.x_posts (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  author_name text not null,
  author_handle text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists x_post_comments_post_id_idx
  on public.x_post_comments (post_id, created_at asc);

create index if not exists x_post_comments_user_id_idx
  on public.x_post_comments (user_id);

create table if not exists public.x_post_likes (
  id integer generated by default as identity primary key,
  post_id integer not null references public.x_posts (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists x_post_likes_post_id_idx
  on public.x_post_likes (post_id);

create index if not exists x_post_likes_user_id_idx
  on public.x_post_likes (user_id);

create table if not exists public.x_post_reposts (
  id integer generated by default as identity primary key,
  post_id integer not null references public.x_posts (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists x_post_reposts_post_id_idx
  on public.x_post_reposts (post_id);

create index if not exists x_post_reposts_user_id_idx
  on public.x_post_reposts (user_id);

create table if not exists public.x_post_shares (
  id integer generated by default as identity primary key,
  post_id integer not null references public.x_posts (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  share_mode text not null default 'system' check (share_mode in ('system', 'copy-link', 'copy-post', 'other')),
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists x_post_shares_post_id_idx
  on public.x_post_shares (post_id);

create index if not exists x_post_shares_user_id_idx
  on public.x_post_shares (user_id);

alter table public.user_profile_preferences enable row level security;
alter table public.user_aliases enable row level security;
alter table public.user_follows enable row level security;
alter table public.x_posts enable row level security;
alter table public.x_post_comments enable row level security;
alter table public.x_post_likes enable row level security;
alter table public.x_post_reposts enable row level security;
alter table public.x_post_shares enable row level security;

drop policy if exists user_profile_preferences_select_own on public.user_profile_preferences;
create policy user_profile_preferences_select_own
  on public.user_profile_preferences
  for select
  using (auth.uid() = user_id);

drop policy if exists user_profile_preferences_insert_own on public.user_profile_preferences;
create policy user_profile_preferences_insert_own
  on public.user_profile_preferences
  for insert
  with check (auth.uid() = user_id);

drop policy if exists user_profile_preferences_update_own on public.user_profile_preferences;
create policy user_profile_preferences_update_own
  on public.user_profile_preferences
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_aliases_select_own on public.user_aliases;
create policy user_aliases_select_own
  on public.user_aliases
  for select
  using (auth.uid() = user_id);

drop policy if exists user_aliases_insert_own on public.user_aliases;
create policy user_aliases_insert_own
  on public.user_aliases
  for insert
  with check (auth.uid() = user_id);

drop policy if exists user_aliases_update_own on public.user_aliases;
create policy user_aliases_update_own
  on public.user_aliases
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists user_aliases_delete_own on public.user_aliases;
create policy user_aliases_delete_own
  on public.user_aliases
  for delete
  using (auth.uid() = user_id);

drop policy if exists user_follows_select_all on public.user_follows;
create policy user_follows_select_all
  on public.user_follows
  for select
  using (true);

drop policy if exists user_follows_insert_own on public.user_follows;
create policy user_follows_insert_own
  on public.user_follows
  for insert
  with check (auth.uid() = follower_id);

drop policy if exists user_follows_delete_own on public.user_follows;
create policy user_follows_delete_own
  on public.user_follows
  for delete
  using (auth.uid() = follower_id);

drop policy if exists x_posts_select_all on public.x_posts;
create policy x_posts_select_all
  on public.x_posts
  for select
  using (true);

drop policy if exists x_posts_insert_own on public.x_posts;
create policy x_posts_insert_own
  on public.x_posts
  for insert
  with check (auth.uid() = author_id);

drop policy if exists x_posts_update_own on public.x_posts;
create policy x_posts_update_own
  on public.x_posts
  for update
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists x_posts_delete_own on public.x_posts;
create policy x_posts_delete_own
  on public.x_posts
  for delete
  using (auth.uid() = author_id);

drop policy if exists x_post_comments_select_all on public.x_post_comments;
create policy x_post_comments_select_all
  on public.x_post_comments
  for select
  using (true);

drop policy if exists x_post_comments_insert_own on public.x_post_comments;
create policy x_post_comments_insert_own
  on public.x_post_comments
  for insert
  with check (auth.uid() = user_id);

drop policy if exists x_post_comments_update_own on public.x_post_comments;
create policy x_post_comments_update_own
  on public.x_post_comments
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists x_post_comments_delete_own on public.x_post_comments;
create policy x_post_comments_delete_own
  on public.x_post_comments
  for delete
  using (auth.uid() = user_id);

drop policy if exists x_post_likes_select_all on public.x_post_likes;
create policy x_post_likes_select_all
  on public.x_post_likes
  for select
  using (true);

drop policy if exists x_post_likes_insert_own on public.x_post_likes;
create policy x_post_likes_insert_own
  on public.x_post_likes
  for insert
  with check (auth.uid() = user_id);

drop policy if exists x_post_likes_delete_own on public.x_post_likes;
create policy x_post_likes_delete_own
  on public.x_post_likes
  for delete
  using (auth.uid() = user_id);

drop policy if exists x_post_reposts_select_all on public.x_post_reposts;
create policy x_post_reposts_select_all
  on public.x_post_reposts
  for select
  using (true);

drop policy if exists x_post_reposts_insert_own on public.x_post_reposts;
create policy x_post_reposts_insert_own
  on public.x_post_reposts
  for insert
  with check (auth.uid() = user_id);

drop policy if exists x_post_reposts_delete_own on public.x_post_reposts;
create policy x_post_reposts_delete_own
  on public.x_post_reposts
  for delete
  using (auth.uid() = user_id);

drop policy if exists x_post_shares_select_all on public.x_post_shares;
create policy x_post_shares_select_all
  on public.x_post_shares
  for select
  using (true);

drop policy if exists x_post_shares_insert_own on public.x_post_shares;
create policy x_post_shares_insert_own
  on public.x_post_shares
  for insert
  with check (auth.uid() = user_id);

drop policy if exists x_post_shares_delete_own on public.x_post_shares;
create policy x_post_shares_delete_own
  on public.x_post_shares
  for delete
  using (auth.uid() = user_id);

alter table public.videos
  add column if not exists user_id uuid references public.users (id) on delete set null;

alter table public.videos
  add column if not exists creator_name text;

alter table public.videos
  add column if not exists creator_handle text;

alter table public.videos
  add column if not exists creator_avatar_url text;

alter table public.videos
  add column if not exists creator_avatar_frame_enabled boolean not null default false;

alter table public.videos
  add column if not exists created_at timestamptz not null default now();

create index if not exists videos_user_id_created_at_idx
  on public.videos (user_id, created_at desc);

create table if not exists public.video_comments (
  id bigint generated by default as identity primary key,
  video_id integer not null references public.videos (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  author_name text not null,
  author_handle text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists video_comments_video_id_idx
  on public.video_comments (video_id, created_at asc);

create index if not exists video_comments_user_id_idx
  on public.video_comments (user_id);

create table if not exists public.video_likes (
  id bigint generated by default as identity primary key,
  video_id integer not null references public.videos (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (video_id, user_id)
);

create index if not exists video_likes_video_id_idx
  on public.video_likes (video_id);

create index if not exists video_likes_user_id_idx
  on public.video_likes (user_id);

create table if not exists public.video_saves (
  id bigint generated by default as identity primary key,
  video_id integer not null references public.videos (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (video_id, user_id)
);

create index if not exists video_saves_video_id_idx
  on public.video_saves (video_id);

create index if not exists video_saves_user_id_idx
  on public.video_saves (user_id);

create table if not exists public.video_shares (
  id bigint generated by default as identity primary key,
  video_id integer not null references public.videos (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  share_mode text not null default 'system' check (share_mode in ('system', 'copy-link', 'copy-video', 'other')),
  created_at timestamptz not null default now(),
  unique (video_id, user_id)
);

create index if not exists video_shares_video_id_idx
  on public.video_shares (video_id);

create index if not exists video_shares_user_id_idx
  on public.video_shares (user_id);

create table if not exists public.fan_team_supports (
  id bigint generated by default as identity primary key,
  team_id text not null check (team_id in ('hilal', 'nassr', 'ittihad')),
  user_id uuid not null references public.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (team_id, user_id)
);

create index if not exists fan_team_supports_team_id_idx
  on public.fan_team_supports (team_id);

create index if not exists fan_team_supports_user_id_idx
  on public.fan_team_supports (user_id);

alter table public.videos enable row level security;
alter table public.video_comments enable row level security;
alter table public.video_likes enable row level security;
alter table public.video_saves enable row level security;
alter table public.video_shares enable row level security;
alter table public.fan_team_supports enable row level security;

drop policy if exists videos_select_all on public.videos;
create policy videos_select_all
  on public.videos
  for select
  using (true);

drop policy if exists videos_insert_own on public.videos;
create policy videos_insert_own
  on public.videos
  for insert
  with check (user_id is null or auth.uid() = user_id);

drop policy if exists videos_update_own on public.videos;
create policy videos_update_own
  on public.videos
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists videos_delete_own on public.videos;
create policy videos_delete_own
  on public.videos
  for delete
  using (auth.uid() = user_id);

drop policy if exists video_comments_select_all on public.video_comments;
create policy video_comments_select_all
  on public.video_comments
  for select
  using (true);

drop policy if exists video_comments_insert_own on public.video_comments;
create policy video_comments_insert_own
  on public.video_comments
  for insert
  with check (auth.uid() = user_id);

drop policy if exists video_comments_update_own on public.video_comments;
create policy video_comments_update_own
  on public.video_comments
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists video_comments_delete_own on public.video_comments;
create policy video_comments_delete_own
  on public.video_comments
  for delete
  using (auth.uid() = user_id);

drop policy if exists video_likes_select_all on public.video_likes;
create policy video_likes_select_all
  on public.video_likes
  for select
  using (true);

drop policy if exists video_likes_insert_own on public.video_likes;
create policy video_likes_insert_own
  on public.video_likes
  for insert
  with check (auth.uid() = user_id);

drop policy if exists video_likes_delete_own on public.video_likes;
create policy video_likes_delete_own
  on public.video_likes
  for delete
  using (auth.uid() = user_id);

drop policy if exists fan_team_supports_select_all on public.fan_team_supports;
create policy fan_team_supports_select_all
  on public.fan_team_supports
  for select
  using (true);

drop policy if exists fan_team_supports_insert_own on public.fan_team_supports;
create policy fan_team_supports_insert_own
  on public.fan_team_supports
  for insert
  with check (auth.uid() = user_id);

drop policy if exists fan_team_supports_delete_own on public.fan_team_supports;
create policy fan_team_supports_delete_own
  on public.fan_team_supports
  for delete
  using (auth.uid() = user_id);

drop policy if exists video_saves_select_all on public.video_saves;
create policy video_saves_select_all
  on public.video_saves
  for select
  using (true);

drop policy if exists video_saves_insert_own on public.video_saves;
create policy video_saves_insert_own
  on public.video_saves
  for insert
  with check (auth.uid() = user_id);

drop policy if exists video_saves_delete_own on public.video_saves;
create policy video_saves_delete_own
  on public.video_saves
  for delete
  using (auth.uid() = user_id);

drop policy if exists video_shares_select_all on public.video_shares;
create policy video_shares_select_all
  on public.video_shares
  for select
  using (true);

drop policy if exists video_shares_insert_own on public.video_shares;
create policy video_shares_insert_own
  on public.video_shares
  for insert
  with check (auth.uid() = user_id);

drop policy if exists video_shares_delete_own on public.video_shares;
create policy video_shares_delete_own
  on public.video_shares
  for delete
  using (auth.uid() = user_id);

alter table public.groups
  add column if not exists dm_key text;

alter table public.groups
  add column if not exists last_message text;

alter table public.groups
  add column if not exists last_message_at timestamptz;

create unique index if not exists groups_dm_key_idx
  on public.groups (dm_key)
  where dm_key is not null;

create index if not exists groups_last_message_at_idx
  on public.groups (last_message_at desc);

create table if not exists public.group_read_states (
  group_id uuid not null references public.groups (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create index if not exists group_read_states_user_id_idx
  on public.group_read_states (user_id, last_read_at desc);

alter table public.group_read_states enable row level security;

drop policy if exists group_read_states_select_own on public.group_read_states;
create policy group_read_states_select_own
  on public.group_read_states
  for select
  using (auth.uid() = user_id);

drop policy if exists group_read_states_insert_own on public.group_read_states;
create policy group_read_states_insert_own
  on public.group_read_states
  for insert
  with check (auth.uid() = user_id);

drop policy if exists group_read_states_update_own on public.group_read_states;
create policy group_read_states_update_own
  on public.group_read_states
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.sync_group_last_message_from_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  next_group_id uuid;
  next_body text;
  next_created_at timestamptz;
begin
  if to_jsonb(new) ->> 'group_id' is null then
    return new;
  end if;

  next_group_id := (to_jsonb(new) ->> 'group_id')::uuid;
  next_body := coalesce(to_jsonb(new) ->> 'text', to_jsonb(new) ->> 'content', '');
  next_created_at := coalesce((to_jsonb(new) ->> 'created_at')::timestamptz, now());

  update public.groups
    set last_message = left(next_body, 500),
        last_message_at = next_created_at
  where id = next_group_id;

  return new;
end;
$$;

drop trigger if exists messages_sync_group_last_message on public.messages;
create trigger messages_sync_group_last_message
after insert on public.messages
for each row execute function public.sync_group_last_message_from_message();

create table if not exists public.admin_reports (
  id uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('x_post', 'video', 'group', 'user', 'comment', 'message')),
  target_id text not null,
  source text not null,
  summary text not null,
  reason text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'resolved', 'dismissed')),
  reporter_label text,
  created_by uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_reports_status_created_at_idx
  on public.admin_reports (status, created_at desc);

create index if not exists admin_reports_target_idx
  on public.admin_reports (target_type, target_id);

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  target_type text not null,
  target_id text not null,
  details text not null,
  actor_label text not null,
  actor_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);

create table if not exists public.user_verifications (
  user_id uuid primary key references public.users (id) on delete cascade,
  badge text not null check (badge in ('yellow', 'blue')),
  updated_at timestamptz not null default now(),
  updated_by text not null
);

create index if not exists user_verifications_updated_at_idx
  on public.user_verifications (updated_at desc);

alter table public.admin_reports enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.user_verifications enable row level security;

drop policy if exists admin_reports_insert_authenticated on public.admin_reports;
create policy admin_reports_insert_authenticated
  on public.admin_reports
  for insert
  with check (auth.role() = 'authenticated' and (created_by is null or auth.uid() = created_by));

drop policy if exists user_verifications_select_all on public.user_verifications;
create policy user_verifications_select_all
  on public.user_verifications
  for select
  using (true);

select pg_notify('pgrst', 'reload schema');