import type {
  FanClub,
  FanClubId,
  HomeMode,
  MatchEvent,
  NewsItem,
  Palette,
  Post,
  ProfileData,
  TacticalPlayer,
  Video,
  BenchPlayer,
} from "./app.types";
import { getConfiguredWalletPassUrl } from "./wallet/pass-url";

export const HOME_PALETTES: Record<HomeMode, Palette> = {
  tiktok: {
    accent: "#FF7E67",
    panel: "#120C10",
    gradient: ["#F84868", "#FFAD54"],
    label: "TikTok",
  },
  x: {
    accent: "#7ADFFF",
    panel: "#081823",
    gradient: ["#4CC4FF", "#C0F4FF"],
    label: "X",
  },
};

export const INITIAL_VIDEOS: Video[] = [
  {
    id: 1,
    creatorName: "Xtik",
    creatorHandle: "@xtik",
    caption:
      "لقطة سريعة من نبض المباراة مع نفس المزاج الكامل لواجهة TikTok داخل التطبيق.",
    likes: 128,
    saves: 24,
    shares: 11,
    comments: 19,
    likedByMe: false,
    savedByMe: false,
    sharedByMe: false,
    theme: ["#187DD2", "#061427"],
    tag: "Ocean",
  },
  {
    id: 2,
    creatorName: "WEBPLUS",
    creatorHandle: "@webplus",
    caption:
      "نسخة Expo الآن تعرض البوستر الكبير، dock جانبي، ومعلومات المنشئ في أسفل المشهد.",
    likes: 94,
    saves: 16,
    shares: 8,
    comments: 11,
    likedByMe: true,
    savedByMe: true,
    sharedByMe: false,
    theme: ["#FF6C58", "#32110E"],
    tag: "Ember",
  },
  {
    id: 3,
    creatorName: "Match Hub",
    creatorHandle: "@matchhub",
    caption:
      "الخلفيات ما زالت تجريبية، لكن لغة الحركة والزجاج الداكنة صارت أقرب للهوية البصرية المستهدفة.",
    likes: 67,
    saves: 13,
    shares: 4,
    comments: 7,
    likedByMe: false,
    savedByMe: false,
    sharedByMe: false,
    theme: ["#14D691", "#051915"],
    tag: "Neon",
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 1,
    author: "VAR X",
    handle: "@varx",
    time: "الآن",
    content:
      "تم نقل شريط X العلوي والبطاقات الداكنة والحالة البصرية إلى Expo مع الاحتفاظ بنفس التبويب العام.",
    likes: 18,
    replies: 2,
    reposts: 5,
    shares: 1,
    likedByMe: false,
  },
  {
    id: 2,
    author: "WEBPLUS",
    handle: "@webplus",
    time: "قبل 5 دقائق",
    content:
      "الهدف الآن ليس فقط تشغيل المشروع، بل ضبط التفاصيل البصرية: header bar، drawer، وتكوين المنشور.",
    likes: 9,
    replies: 1,
    reposts: 2,
    shares: 0,
    likedByMe: true,
  },
  {
    id: 3,
    author: "Build Notes",
    handle: "@build_notes",
    time: "قبل 12 دقيقة",
    content:
      "النسخة الحالية صارت مركزة بالكامل على Expo مع الحفاظ على التدرج البصري نفسه خطوة بخطوة.",
    likes: 6,
    replies: 0,
    reposts: 1,
    shares: 0,
    likedByMe: false,
  },
];

export const FAN_CLUBS: FanClub[] = [
  { id: "hilal",        leagueId: "saudi",   title: "الهلال",              crowdLabel: "جمهور الهلال",              summary: "صعود ثابت في ترند الرابطة.",        trendLabel: "الأكثر تفاعلًا",  gradient: ["#0B47BC", "#041125"], icon: "moon" },
  { id: "nassr",        leagueId: "saudi",   title: "النصر",               crowdLabel: "جمهور النصر",               summary: "موجة اقتباسات كبيرة.",             trendLabel: "ترند صاعد",       gradient: ["#B38727", "#231A05"], icon: "sunny" },
  { id: "ittihad",      leagueId: "saudi",   title: "الاتحاد",             crowdLabel: "جمهور الاتحاد",             summary: "ثبات يومي في التفاعل.",             trendLabel: "ثبات قوي",        gradient: ["#C59037", "#281806"], icon: "shield" },
  { id: "ahli",         leagueId: "saudi",   title: "الأهلي",              crowdLabel: "جمهور الأهلي",              summary: "زخم جماهيري متصاعد.",              trendLabel: "صعود جماهيري",    gradient: ["#0A6B4F", "#031912"], icon: "leaf" },
  { id: "shabab",       leagueId: "saudi",   title: "الشباب",              crowdLabel: "جمهور الشباب",              summary: "نشاط مستمر في الرابطة.",           trendLabel: "زخم مستقر",       gradient: ["#6B2D84", "#18071F"], icon: "flash" },
  { id: "ittefaq",      leagueId: "saudi",   title: "الاتفاق",             crowdLabel: "جمهور الاتفاق",             summary: "حضور متصاعد في المنصات.",          trendLabel: "نشاط جيد",        gradient: ["#1A6B3A", "#051510"], icon: "football" },
  { id: "qadisiyah",    leagueId: "saudi",   title: "القادسية",            crowdLabel: "جمهور القادسية",            summary: "تفاعل منتظم من الجمهور.",          trendLabel: "ثبات",            gradient: ["#1A4A8A", "#050D1F"], icon: "flag" },
  { id: "raed",         leagueId: "saudi",   title: "الرائد",              crowdLabel: "جمهور الرائد",              summary: "مشاركة جيدة في اللحظات الحرجة.",  trendLabel: "صاعد",            gradient: ["#8A1A1A", "#1F0505"], icon: "trending-up" },
  { id: "fayha",        leagueId: "saudi",   title: "الفيحاء",             crowdLabel: "جمهور الفيحاء",             summary: "جمهور وفي ونشط.",                  trendLabel: "منتظم",           gradient: ["#2A5A1A", "#071005"], icon: "leaf" },
  { id: "damak",        leagueId: "saudi",   title: "ضمك",                 crowdLabel: "جمهور ضمك",                 summary: "حضور رقمي متنامٍ.",               trendLabel: "نامٍ",            gradient: ["#5A1A8A", "#100518"], icon: "stats-chart" },
  { id: "tai",          leagueId: "saudi",   title: "الطائي",              crowdLabel: "جمهور الطائي",              summary: "قاعدة جماهيرية صلبة.",             trendLabel: "مستقر",           gradient: ["#8A4A1A", "#1F0D05"], icon: "shield-half" },
  { id: "khaleej",      leagueId: "saudi",   title: "الخليج",              crowdLabel: "جمهور الخليج",              summary: "تفاعل موسمي واضح.",               trendLabel: "موسمي",           gradient: ["#1A5A8A", "#05101F"], icon: "water" },
  { id: "abha",         leagueId: "saudi",   title: "أبها",                crowdLabel: "جمهور أبها",                summary: "جمهور منظّم ومخلص.",              trendLabel: "وفيّ",            gradient: ["#1A8A5A", "#051F10"], icon: "leaf" },
  { id: "taawun",       leagueId: "saudi",   title: "التعاون",             crowdLabel: "جمهور التعاون",             summary: "نشاط واضح في المباريات الكبرى.",  trendLabel: "نشط",             gradient: ["#8A8A1A", "#1F1F05"], icon: "people" },
  { id: "fateh",        leagueId: "saudi",   title: "الفتح",               crowdLabel: "جمهور الفتح",               summary: "حضور ثابت طوال الموسم.",           trendLabel: "ثابت",            gradient: ["#8A1A4A", "#1F0510"], icon: "trophy" },
  { id: "wehda",        leagueId: "saudi",   title: "الوحدة",              crowdLabel: "جمهور الوحدة",              summary: "تفاعل جيد في الملاعب.",           trendLabel: "جماهيري",         gradient: ["#1A8A8A", "#051F1F"], icon: "heart" },
  { id: "mancity",      leagueId: "premier", title: "مانشستر سيتي",       crowdLabel: "جمهور السيتي",              summary: "حضور قوي في الرابطة.",             trendLabel: "الأكثر تفاعلًا",  gradient: ["#6CAEE0", "#0E1E30"], icon: "moon" },
  { id: "manutd",       leagueId: "premier", title: "مانشستر يونايتد",    crowdLabel: "جمهور اليونايتد",           summary: "قاعدة جماهيرية ضخمة.",             trendLabel: "ترند صاعد",       gradient: ["#C0392B", "#2C0B08"], icon: "flame" },
  { id: "liverpool",    leagueId: "premier", title: "ليفربول",             crowdLabel: "جمهور ليفربول",             summary: "تفاعل لا يتوقف.",                  trendLabel: "نشط جداً",        gradient: ["#C0392B", "#2C0B08"], icon: "heart" },
  { id: "chelsea",      leagueId: "premier", title: "تشيلسي",             crowdLabel: "جمهور تشيلسي",              summary: "مشاركة عالية.",                    trendLabel: "ثبات قوي",        gradient: ["#1A4FC0", "#060E2C"], icon: "shield" },
  { id: "arsenal",      leagueId: "premier", title: "أرسنال",              crowdLabel: "جمهور أرسنال",              summary: "زخم متصاعد.",                      trendLabel: "صعود جماهيري",    gradient: ["#C01A1A", "#2C0606"], icon: "flame" },
  { id: "tottenham",    leagueId: "premier", title: "توتنهام",             crowdLabel: "جمهور توتنهام",             summary: "حضور رقمي جيد.",                   trendLabel: "منتظم",           gradient: ["#132257", "#050B22"], icon: "star" },
  { id: "newcastle",    leagueId: "premier", title: "نيوكاسل",             crowdLabel: "جمهور نيوكاسل",             summary: "نشاط متزايد.",                     trendLabel: "نامٍ",            gradient: ["#241F20", "#0A0809"], icon: "contrast" },
  { id: "astonvilla",   leagueId: "premier", title: "أستون فيلا",          crowdLabel: "جمهور فيلا",                summary: "جمهور وفيّ.",                      trendLabel: "وفيّ",            gradient: ["#95BFE5", "#1A3D5C"], icon: "leaf" },
  { id: "westham",      leagueId: "premier", title: "ويست هام",            crowdLabel: "جمهور ويست هام",            summary: "تفاعل موسمي واضح.",               trendLabel: "موسمي",           gradient: ["#7A263A", "#1F0810"], icon: "hammer" },
  { id: "brighton",     leagueId: "premier", title: "برايتون",             crowdLabel: "جمهور برايتون",             summary: "قاعدة صاعدة.",                     trendLabel: "صاعد",            gradient: ["#005daa", "#001D35"], icon: "sunny" },
  { id: "bournemouth",  leagueId: "premier", title: "بورنموث",             crowdLabel: "جمهور بورنموث",             summary: "مشاركة جيدة.",                     trendLabel: "جيد",             gradient: ["#DA291C", "#350A07"], icon: "flag" },
  { id: "leicester",    leagueId: "premier", title: "ليستر سيتي",          crowdLabel: "جمهور ليستر",               summary: "حضور ثابت.",                       trendLabel: "ثابت",            gradient: ["#003090", "#000E2C"], icon: "shield" },
  { id: "everton",      leagueId: "premier", title: "إيفرتون",             crowdLabel: "جمهور إيفرتون",             summary: "جمهور أزرق نشط.",                  trendLabel: "نشط",             gradient: ["#003399", "#00092E"], icon: "shield" },
  { id: "wolves",       leagueId: "premier", title: "ولفرهامبتون",         crowdLabel: "جمهور وولفز",               summary: "تفاعل ثابت.",                      trendLabel: "ثابت",            gradient: ["#FDB913", "#4A3800"], icon: "paw" },
  { id: "crystalpalace",leagueId: "premier", title: "كريستال بالاس",       crowdLabel: "جمهور كريستال",             summary: "ألوان حية ونشاط جيد.",             trendLabel: "جيد",             gradient: ["#1B458F", "#07162E"], icon: "diamond" },
  { id: "nottingham",   leagueId: "premier", title: "نوتينغهام فورست",     crowdLabel: "جمهور فورست",               summary: "حضور تاريخي راسخ.",               trendLabel: "راسخ",            gradient: ["#C8102E", "#30040B"], icon: "leaf" },
  { id: "fulham",       leagueId: "premier", title: "فولهام",              crowdLabel: "جمهور فولهام",              summary: "تفاعل منتظم.",                     trendLabel: "منتظم",           gradient: ["#CC0000", "#300000"], icon: "football" },
  { id: "brentford",    leagueId: "premier", title: "برنتفورد",            crowdLabel: "جمهور برنتفورد",            summary: "قاعدة جماهيرية صاعدة.",           trendLabel: "صاعد",            gradient: ["#E30613", "#380105"], icon: "flash" },
  { id: "southampton",  leagueId: "premier", title: "ساوثهامبتون",         crowdLabel: "جمهور ساوثهامبتون",         summary: "مشاركة جيدة.",                     trendLabel: "جيد",             gradient: ["#D71920", "#340607"], icon: "boat" },
  { id: "ipswich",      leagueId: "premier", title: "ايبسويش",             crowdLabel: "جمهور ايبسويش",             summary: "عودة قوية للدوري.",               trendLabel: "عائد",            gradient: ["#0044AA", "#001030"], icon: "trending-up" },
  { id: "realmadrid",   leagueId: "laliga",  title: "ريال مدريد",          crowdLabel: "جمهور الريال",              summary: "أضخم جمهور في العالم.",           trendLabel: "الأكثر تفاعلًا",  gradient: ["#FEBE10", "#3D2E00"], icon: "trophy" },
  { id: "barcelona",    leagueId: "laliga",  title: "برشلونة",             crowdLabel: "جمهور برشلونة",             summary: "قاعدة جماهيرية عالمية.",           trendLabel: "ترند صاعد",       gradient: ["#A50044", "#2C0011"], icon: "heart" },
  { id: "atletico",     leagueId: "laliga",  title: "أتلتيكو مدريد",       crowdLabel: "جمهور أتلتيكو",             summary: "شغف لا يهدأ.",                     trendLabel: "نشط جداً",        gradient: ["#CE3524", "#310D08"], icon: "flame" },
  { id: "sevilla",      leagueId: "laliga",  title: "إشبيلية",             crowdLabel: "جمهور إشبيلية",             summary: "تفاعل قوي في الكأس.",             trendLabel: "ثبات قوي",        gradient: ["#C8102E", "#30040B"], icon: "shield" },
  { id: "villarreal",   leagueId: "laliga",  title: "فياريال",             crowdLabel: "جمهور فياريال",             summary: "غواصة صفراء نشطة.",               trendLabel: "نشط",             gradient: ["#FFD700", "#3D3300"], icon: "sunny" },
  { id: "betis",        leagueId: "laliga",  title: "بيتيس",               crowdLabel: "جمهور بيتيس",               summary: "جمهور أخضر مخلص.",                trendLabel: "مخلص",            gradient: ["#00954C", "#002917"], icon: "leaf" },
  { id: "sociedad",     leagueId: "laliga",  title: "سوسيداد",             crowdLabel: "جمهور سوسيداد",             summary: "تفاعل ثقافي راقٍ.",               trendLabel: "راقٍ",            gradient: ["#2684C8", "#092434"], icon: "water" },
  { id: "athleticbilbao",leagueId: "laliga", title: "أتلتيك بلباو",        crowdLabel: "جمهور بلباو",               summary: "هوية قوية وجمهور فخور.",          trendLabel: "فخور",            gradient: ["#C8102E", "#30040B"], icon: "flag" },
  { id: "valencia",     leagueId: "laliga",  title: "فالنسيا",             crowdLabel: "جمهور فالنسيا",             summary: "شعلة من المشجعين.",               trendLabel: "متوهج",           gradient: ["#FF7700", "#3D1C00"], icon: "flame" },
  { id: "osasuna",      leagueId: "laliga",  title: "أوساسونا",            crowdLabel: "جمهور أوساسونا",            summary: "تفاعل محلي قوي.",                 trendLabel: "محلي",            gradient: ["#C8102E", "#30040B"], icon: "heart" },
  { id: "alaves",       leagueId: "laliga",  title: "ألاباس",              crowdLabel: "جمهور ألاباس",              summary: "صعود واضح.",                       trendLabel: "صاعد",            gradient: ["#004A97", "#001630"], icon: "trending-up" },
  { id: "mallorca",     leagueId: "laliga",  title: "مايوركا",             crowdLabel: "جمهور مايوركا",             summary: "جمهور جزيرة حار.",                trendLabel: "حار",             gradient: ["#C8102E", "#30040B"], icon: "sunny" },
  { id: "celtavigo",    leagueId: "laliga",  title: "سيلتا فيغو",          crowdLabel: "جمهور سيلتا",               summary: "تفاعل ثابت.",                      trendLabel: "ثابت",            gradient: ["#87CEEB", "#1A3E50"], icon: "water" },
  { id: "leganes",      leagueId: "laliga",  title: "ليغانيس",             crowdLabel: "جمهور ليغانيس",             summary: "عودة قوية.",                       trendLabel: "عائد",            gradient: ["#003087", "#00092A"], icon: "football" },
  { id: "getafe",       leagueId: "laliga",  title: "خيتافي",              crowdLabel: "جمهور خيتافي",              summary: "تنظيم ودفاع قوي.",                trendLabel: "صلب",             gradient: ["#0054A6", "#001830"], icon: "shield" },
  { id: "espanyol",     leagueId: "laliga",  title: "إسبانيول",            crowdLabel: "جمهور إسبانيول",            summary: "هوية كتالونية مستقلة.",           trendLabel: "مستقل",           gradient: ["#003DA5", "#001230"], icon: "flag" },
  { id: "rayo",         leagueId: "laliga",  title: "رايو فاليكانو",       crowdLabel: "جمهور رايو",                summary: "روح شعبية نابضة.",                trendLabel: "شعبي",            gradient: ["#C8102E", "#30040B"], icon: "flash" },
  { id: "valladolid",   leagueId: "laliga",  title: "فالادوليد",           crowdLabel: "جمهور فالادوليد",           summary: "حضور تاريخي.",                     trendLabel: "تاريخي",          gradient: ["#720E6B", "#1C0419"], icon: "trophy" },
  { id: "laspalmas",    leagueId: "laliga",  title: "لاس بالماس",          crowdLabel: "جمهور لاس بالماس",          summary: "جمهور جزر الكناري.",              trendLabel: "مخلص",            gradient: ["#FFD700", "#3D3300"], icon: "sunny" },
  { id: "girona",       leagueId: "laliga",  title: "خيرونا",              crowdLabel: "جمهور خيرونا",              summary: "قصة صعود ملهمة.",                 trendLabel: "ملهم",            gradient: ["#9B1D20", "#26080A"], icon: "trending-up" },
  { id: "psg",          leagueId: "ligue1",  title: "باريس سان جيرمان",    crowdLabel: "جمهور PSG",                 summary: "النجوم والجمهور معاً.",           trendLabel: "الأكثر تفاعلًا",  gradient: ["#003087", "#00092A"], icon: "star" },
  { id: "marseille",    leagueId: "ligue1",  title: "مرسيليا",             crowdLabel: "جمهور مرسيليا",             summary: "أكثر جماهير فرنسا حرارةً.",       trendLabel: "حار جداً",        gradient: ["#00A4E4", "#003A50"], icon: "flame" },
  { id: "monaco",       leagueId: "ligue1",  title: "موناكو",              crowdLabel: "جمهور موناكو",              summary: "تفاعل فاخر.",                      trendLabel: "فاخر",            gradient: ["#C8102E", "#30040B"], icon: "diamond" },
  { id: "lyon",         leagueId: "ligue1",  title: "ليون",                crowdLabel: "جمهور ليون",                summary: "قاعدة جماهيرية صلبة.",             trendLabel: "صلب",             gradient: ["#B5121B", "#2C0508"], icon: "heart" },
  { id: "lille",        leagueId: "ligue1",  title: "ليل",                 crowdLabel: "جمهور ليل",                 summary: "ألتراس شمال فرنسا.",              trendLabel: "قوي",             gradient: ["#C8102E", "#30040B"], icon: "shield" },
  { id: "nice",         leagueId: "ligue1",  title: "نيس",                 crowdLabel: "جمهور نيس",                 summary: "تفاعل ساحلي جميل.",               trendLabel: "منتظم",           gradient: ["#BE0000", "#2C0000"], icon: "sunny" },
  { id: "rennes",       leagueId: "ligue1",  title: "رين",                 crowdLabel: "جمهور رين",                 summary: "حضور برتوني قوي.",                trendLabel: "جيد",             gradient: ["#000000", "#1A1A1A"], icon: "flag" },
  { id: "strasbourg",   leagueId: "ligue1",  title: "ستراسبورغ",           crowdLabel: "جمهور ستراسبورغ",           summary: "روح ألزاسية فريدة.",              trendLabel: "فريد",            gradient: ["#1D439C", "#070F2C"], icon: "water" },
  { id: "montpellier",  leagueId: "ligue1",  title: "مونبلييه",            crowdLabel: "جمهور مونبلييه",            summary: "نشاط جنوبي دافئ.",                trendLabel: "دافئ",            gradient: ["#F7A800", "#3D2900"], icon: "sunny" },
  { id: "nantes",       leagueId: "ligue1",  title: "نانت",                crowdLabel: "جمهور نانت",                summary: "ألوان صفراء تشع.",                trendLabel: "مشرق",            gradient: ["#F5A623", "#3D2900"], icon: "flash" },
  { id: "bordeaux",     leagueId: "ligue1",  title: "بوردو",               crowdLabel: "جمهور بوردو",               summary: "تاريخ راسخ.",                      trendLabel: "تاريخي",          gradient: ["#1B1464", "#070519"], icon: "trophy" },
  { id: "lens",         leagueId: "ligue1",  title: "لانس",                crowdLabel: "جمهور لانس",                summary: "أشد مشجعين في الدوري.",           trendLabel: "متحمس",           gradient: ["#E30613", "#380105"], icon: "flame" },
  { id: "toulouse",     leagueId: "ligue1",  title: "تولوز",               crowdLabel: "جمهور تولوز",               summary: "حضور بنفسجي مميز.",               trendLabel: "مميز",            gradient: ["#6A0F8E", "#1A0422"], icon: "star" },
  { id: "angers",       leagueId: "ligue1",  title: "أنجيه",               crowdLabel: "جمهور أنجيه",               summary: "تفاعل محلي مخلص.",                trendLabel: "مخلص",            gradient: ["#000000", "#1A1A1A"], icon: "heart" },
  { id: "reims",        leagueId: "ligue1",  title: "ريمس",                crowdLabel: "جمهور ريمس",                summary: "قاعدة جماهيرية صاعدة.",           trendLabel: "صاعد",            gradient: ["#E4002B", "#360009"], icon: "trending-up" },
  { id: "clermont",     leagueId: "ligue1",  title: "كليرمون",             crowdLabel: "جمهور كليرمون",             summary: "حضور متنامٍ.",                    trendLabel: "نامٍ",            gradient: ["#E4002B", "#360009"], icon: "flame" },
  { id: "auxerre",      leagueId: "ligue1",  title: "أوكسير",              crowdLabel: "جمهور أوكسير",              summary: "عودة بعد غياب.",                   trendLabel: "عائد",            gradient: ["#E4002B", "#360009"], icon: "refresh" },
  { id: "brest",        leagueId: "ligue1",  title: "بريست",               crowdLabel: "جمهور بريست",               summary: "نادي الميناء الصاعد.",            trendLabel: "صاعد",            gradient: ["#C8102E", "#30040B"], icon: "boat" },
  { id: "lehavre",      leagueId: "ligue1",  title: "لوهافر",              crowdLabel: "جمهور لوهافر",              summary: "روح ساحلية قوية.",                trendLabel: "قوي",             gradient: ["#1D439C", "#070F2C"], icon: "water" },
  { id: "saintetienne", leagueId: "ligue1",  title: "سانت إيتيان",         crowdLabel: "جمهور سانت إيتيان",         summary: "أسطورة الدوري الفرنسي.",          trendLabel: "أسطوري",          gradient: ["#2E7D32", "#0B1F0C"], icon: "trophy" },
  { id: "juventus",     leagueId: "seriea",  title: "يوفنتوس",             crowdLabel: "جمهور يوفنتوس",             summary: "سيدة إيطاليا الكبرى.",             trendLabel: "الأكثر تفاعلًا",  gradient: ["#000000", "#FFFFFF"], icon: "star" },
  { id: "milan",          leagueId: "seriea",  title: "ميلان",               crowdLabel: "جمهور ميلان",               summary: "روسونيري الأسطوري.",               trendLabel: "ترند صاعد",       gradient: ["#FB090B", "#000000"], icon: "flame" },
  { id: "intermilan",     leagueId: "seriea",  title: "إنتر ميلان",          crowdLabel: "جمهور الإنتر",              summary: "نيرازوري الأزرق والأسود.",         trendLabel: "ثبات قوي",        gradient: ["#010E80", "#000000"], icon: "shield" },
  { id: "napoli",         leagueId: "seriea",  title: "نابولي",              crowdLabel: "جمهور نابولي",              summary: "شغف جنوب إيطاليا.",               trendLabel: "صعود جماهيري",    gradient: ["#12A4D9", "#FFFFFF"], icon: "heart" },
  { id: "roma",           leagueId: "seriea",  title: "روما",                crowdLabel: "جمهور روما",                summary: "ذئاب العاصمة الإيطالية.",         trendLabel: "زخم مستقر",       gradient: ["#8E1F2F", "#F0B41C"], icon: "moon" },
  { id: "lazio",          leagueId: "seriea",  title: "لاتسيو",              crowdLabel: "جمهور لاتسيو",              summary: "النسور الزرقاء العاصمية.",        trendLabel: "ثبات",            gradient: ["#FFFFFF", "#65D0F7"], icon: "airplane" },
  { id: "fiorentina",     leagueId: "seriea",  title: "فيورنتينا",           crowdLabel: "جمهور فيورنتينا",           summary: "البنفسجي الفلورنسي.",              trendLabel: "نشاط جيد",        gradient: ["#482E92", "#FFFFFF"], icon: "leaf" },
  { id: "atalanta",       leagueId: "seriea",  title: "أتالانتا",            crowdLabel: "جمهور أتالانتا",            summary: "الغربان الإيطالية.",              trendLabel: "صاعد",            gradient: ["#1E71B8", "#000000"], icon: "flash" },
  { id: "torino",         leagueId: "seriea",  title: "تورينو",              crowdLabel: "جمهور تورينو",              summary: "ثور تورينو التاريخي.",           trendLabel: "تاريخي",          gradient: ["#8E1F2F", "#FFFFFF"], icon: "trophy" },
  { id: "bologna",        leagueId: "seriea",  title: "بولونيا",             crowdLabel: "جمهور بولونيا",             summary: "روسوبلو البولوني.",               trendLabel: "منتظم",           gradient: ["#A21C26", "#1A3155"], icon: "flag" },
  { id: "sassuolo",       leagueId: "seriea",  title: "ساسولو",              crowdLabel: "جمهور ساسولو",              summary: "النيروفيردي الساسولي.",          trendLabel: "موسمي",           gradient: ["#008000", "#000000"], icon: "star" },
  { id: "udinese",        leagueId: "seriea",  title: "أودينيزي",            crowdLabel: "جمهور أودينيزي",            summary: "الزيبريتي الأودينيزي.",           trendLabel: "نامٍ",            gradient: ["#FFFFFF", "#000000"], icon: "paw" },
  { id: "monza",          leagueId: "seriea",  title: "مونزا",               crowdLabel: "جمهور مونزا",               summary: "الفارس الأحمر الإيطالي.",          trendLabel: "مستقر",           gradient: ["#E32219", "#FFFFFF"], icon: "trophy" },
  { id: "empoli",         leagueId: "seriea",  title: "إمبولي",              crowdLabel: "جمهور إمبولي",              summary: "الأزوري الإمبولي.",               trendLabel: "وفيّ",            gradient: ["#0067A5", "#FFFFFF"], icon: "water" },
  { id: "lecce",          leagueId: "seriea",  title: "ليتشي",               crowdLabel: "جمهور ليتشي",               summary: "الذئاب الليتشية.",               trendLabel: "حار",             gradient: ["#E32219", "#FFEF00"], icon: "sunny" },
  { id: "verona",         leagueId: "seriea",  title: "فيرونا",              crowdLabel: "جمهور فيرونا",              summary: "الماستيفي الإيطالي.",             trendLabel: "فخور",            gradient: ["#FEDD33", "#003395"], icon: "shield" },
  { id: "cagliari",       leagueId: "seriea",  title: "كالياري",             crowdLabel: "جمهور كالياري",             summary: "الأحمر والأزرق السرديني.",        trendLabel: "مخلص",            gradient: ["#B30000", "#FFFFFF"], icon: "globe" },
  { id: "genoa",          leagueId: "seriea",  title: "جنوى",                crowdLabel: "جمهور جنوى",                summary: "الجريفوني الإيطالي.",             trendLabel: "شعبي",            gradient: ["#FFFFFF", "#B30000"], icon: "boat" },
  { id: "frosinone",      leagueId: "seriea",  title: "فروسينوني",           crowdLabel: "جمهور فروسينوني",           summary: "كاناري الصعود الإيطالي.",         trendLabel: "عائد",            gradient: ["#FFEF00", "#006FB9"], icon: "trending-up" },
  { id: "como",           leagueId: "seriea",  title: "كومو",                crowdLabel: "جمهور كومو",                summary: "الأزرق الكومي الصاعد.",          trendLabel: "صاعد",            gradient: ["#006FB9", "#FFFFFF"], icon: "water" },
];

export type LeagueData = {
  id: string;
  name: string;
  clubs: string[];
};

export const LEAGUES: LeagueData[] = [
  {
    id: "saudi",
    name: "الدوري السعودي",
    clubs: [
      "الهلال", "النصر", "الاتحاد", "الأهلي", "الشباب", "الاتفاق",
      "القادسية", "الرائد", "الفيحاء", "ضمك", "الطائي", "الخليج",
      "أبها", "التعاون", "الفتح", "الوحدة",
    ],
  },
  {
    id: "premier",
    name: "الدوري الإنجليزي",
    clubs: [
      "مانشستر سيتي", "مانشستر يونايتد", "ليفربول", "تشيلسي",
      "أرسنال", "توتنهام", "نيوكاسل", "أستون فيلا",
      "ويست هام", "برايتون", "بورنموث", "ليستر سيتي",
      "إيفرتون", "ولفرهامبتون", "كريستال بالاس", "نوتينغهام فورست",
      "فولهام", "برنتفورد", "ساوثهامبتون", "ايبسويش",
    ],
  },
  {
    id: "laliga",
    name: "الدوري الإسباني",
    clubs: [
      "ريال مدريد", "برشلونة", "أتلتيكو مدريد", "إشبيلية",
      "فياريال", "بيتيس", "سوسيداد", "أتلتيك بلباو",
      "فالنسيا", "أوساسونا", "ألاباس", "مايوركا",
      "سيلتا فيغو", "ليغانيس", "خيتافي", "إسبانيول",
      "رايو فاليكانو", "فالادوليد", "لاس بالماس", "خيرونا",
    ],
  },
  {
    id: "ligue1",
    name: "الدوري الفرنسي",
    clubs: [
      "باريس سان جيرمان", "مرسيليا", "موناكو", "ليون",
      "ليل", "نيس", "رين", "ستراسبورغ",
      "مونبلييه", "نانت", "بوردو", "لانس",
      "تولوز", "أنجيه", "ريمس", "كليرمون",
      "أوكسير", "بريست", "لوهافر", "سانت إيتيان",
    ],
  },
  {
    id: "seriea",
    name: "الدوري الإيطالي",
    clubs: [
      "يوفنتوس", "ميلان", "إنتر ميلان", "نابولي",
      "روما", "لاتسيو", "فيورنتينا", "أتالانتا",
      "تورينو", "بولونيا", "مونزا", "أودينيزي",
      "ساسولو", "إمبولي", "ليتشي", "فيرونا",
      "كالياري", "فروسينوني", "جنوى", "كومو",
    ],
  },
];

export const INITIAL_SUPPORTERS: Record<FanClubId, number> = {
  hilal: 1842,   nassr: 1634,   ittihad: 1278, ahli: 1045,   shabab: 892,
  ittefaq: 710,  qadisiyah: 658, raed: 541,    fayha: 487,   damak: 423,
  tai: 389,      khaleej: 364,  abha: 341,     taawun: 312,  fateh: 298,
  wehda: 276,
  mancity: 1720, manutd: 1685,  liverpool: 1653, chelsea: 1412, arsenal: 1398,
  tottenham: 1187, newcastle: 987, astonvilla: 934, westham: 876, brighton: 823,
  bournemouth: 756, leicester: 712, everton: 698, wolves: 645, crystalpalace: 612,
  nottingham: 589, fulham: 567, brentford: 534, southampton: 498, ipswich: 445,
  realmadrid: 1923, barcelona: 1876, atletico: 1423, sevilla: 1123, villarreal: 987,
  betis: 912, sociedad: 845, athleticbilbao: 798, valencia: 756, osasuna: 634,
  alaves: 587, mallorca: 554, celtavigo: 523, leganes: 498, getafe: 467,
  espanyol: 445, rayo: 412, valladolid: 389, laspalmas: 367, girona: 345,
  psg: 1654, marseille: 1423, monaco: 1187, lyon: 1098, lille: 978,
  nice: 867, rennes: 756, strasbourg: 698, montpellier: 645, nantes: 612,
  bordeaux: 589, lens: 567, toulouse: 534, angers: 498, reims: 467,
  clermont: 423, auxerre: 398, brest: 376, lehavre: 354, saintetienne: 332,
  juventus: 1887, milan: 1756, intermilan: 1698, napoli: 1434, roma: 1321,
  lazio: 1098, fiorentina: 987, atalanta: 876, torino: 745, bologna: 678,
  sassuolo: 567, udinese: 534, monza: 487, empoli: 445, lecce: 412,
  verona: 389, cagliari: 367, genoa: 345, frosinone: 298, como: 276,
};

export const MATCH_NEWS: NewsItem[] = [
  {
    id: "n1",
    badge: "عاجل",
    title: "الهلال يراجع شكل الضغط قبل المواجهة القادمة",
    summary:
      "الطاقم الفني ركز على الضغط العكسي وسرعة التحول بعد افتكاك الكرة في الثلث الأوسط.",
    time: "قبل 8 دقائق",
    accent: "#63C6FF",
  },
  {
    id: "n2",
    badge: "متابعة",
    title: "النصر يجهز خطة بديلة في الثلث الأخير",
    summary:
      "العمل الآن على زيادة الكثافة حول الصندوق وخلق حل ثالث خلف المهاجم.",
    time: "قبل 14 دقيقة",
    accent: "#FFBB5B",
  },
  {
    id: "n3",
    badge: "تقارير",
    title: "الاستعداد الصيفي يرفع أسهم بعض الأسماء المحلية",
    summary:
      "المنافسة اشتعلت على مركز الجناح والظهير مع ترقب نافذة انتقالات مبكرة.",
    time: "قبل ساعة",
    accent: "#D283FF",
  },
];

export const MATCH_EVENTS: MatchEvent[] = [
  {
    id: "e1",
    minute: "12'",
    title: "ضغط عالٍ",
    detail: "الهلال يغلق العمق ويستعيد الكرة بسرعة في الثلث الأوسط.",
  },
  {
    id: "e2",
    minute: "29'",
    title: "فرصة خطرة",
    detail: "النصر يصل خلف الظهير الأيسر بتبادل سريع على الطرف.",
  },
  {
    id: "e3",
    minute: "53'",
    title: "تعديل تكتيكي",
    detail: "تحويل الجناح إلى العمق لخلق زيادة عددية أمام منطقة الجزاء.",
  },
  {
    id: "e4",
    minute: "77'",
    title: "تبديل تجريبي",
    detail: "دخول جناح سريع لزيادة العرضيات والضغط على خط الدفاع.",
  },
];

export const PRESSURE_BARS = [20, 20, 21, 22, 24, 25, 27, 29, 31, 29, 24, 20];
export const HOME_SUPPORT = 2578;
export const AWAY_SUPPORT = 1950;

export const HOME_LINEUP: TacticalPlayer[] = [
  {
    id: "h1",
    name: "حارس الهلال",
    number: 37,
    x: 0.5,
    y: 0.12,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h2",
    name: "ظهير أيمن الهلال",
    number: 66,
    x: 0.18,
    y: 0.28,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h3",
    name: "قلب دفاع الهلال 1",
    number: 3,
    x: 0.4,
    y: 0.28,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h4",
    name: "قلب دفاع الهلال 2",
    number: 5,
    x: 0.6,
    y: 0.28,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h5",
    name: "ظهير أيسر الهلال",
    number: 12,
    x: 0.82,
    y: 0.28,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h6",
    name: "محور الهلال",
    number: 8,
    x: 0.28,
    y: 0.49,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h7",
    name: "وسط الهلال",
    number: 16,
    x: 0.5,
    y: 0.49,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h8",
    name: "صانع لعب الهلال",
    number: 10,
    x: 0.72,
    y: 0.49,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h9",
    name: "جناح أيمن الهلال",
    number: 77,
    x: 0.18,
    y: 0.73,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h10",
    name: "مهاجم الهلال",
    number: 9,
    x: 0.5,
    y: 0.78,
    gradient: ["#67C7FF", "#1A48AF"],
  },
  {
    id: "h11",
    name: "جناح أيسر الهلال",
    number: 29,
    x: 0.82,
    y: 0.73,
    gradient: ["#67C7FF", "#1A48AF"],
  },
];

export const AWAY_LINEUP: TacticalPlayer[] = [
  {
    id: "a1",
    name: "حارس النصر",
    number: 44,
    x: 0.5,
    y: 0.88,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a2",
    name: "ظهير أيمن النصر",
    number: 2,
    x: 0.18,
    y: 0.72,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a3",
    name: "قلب دفاع النصر 1",
    number: 4,
    x: 0.4,
    y: 0.72,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a4",
    name: "قلب دفاع النصر 2",
    number: 17,
    x: 0.6,
    y: 0.72,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a5",
    name: "ظهير أيسر النصر",
    number: 13,
    x: 0.82,
    y: 0.72,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a6",
    name: "محور النصر 1",
    number: 6,
    x: 0.33,
    y: 0.54,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a7",
    name: "محور النصر 2",
    number: 14,
    x: 0.67,
    y: 0.54,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a8",
    name: "جناح أيمن النصر",
    number: 11,
    x: 0.18,
    y: 0.34,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a9",
    name: "صانع لعب النصر",
    number: 25,
    x: 0.5,
    y: 0.38,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a10",
    name: "جناح أيسر النصر",
    number: 7,
    x: 0.82,
    y: 0.34,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
  {
    id: "a11",
    name: "مهاجم النصر",
    number: 9,
    x: 0.5,
    y: 0.18,
    gradient: ["#FFD16A", "#9A4E1A"],
  },
];

export const HOME_BENCH: BenchPlayer[] = [
  { id: "hb1", name: "بديل الهلال 1", number: 18 },
  { id: "hb2", name: "بديل الهلال 2", number: 24 },
  { id: "hb3", name: "بديل الهلال 3", number: 31 },
  { id: "hb4", name: "بديل الهلال 4", number: 70 },
  { id: "hb5", name: "بديل الهلال 5", number: 88 },
];

export const AWAY_BENCH: BenchPlayer[] = [
  { id: "ab1", name: "بديل النصر 1", number: 19 },
  { id: "ab2", name: "بديل النصر 2", number: 21 },
  { id: "ab3", name: "بديل النصر 3", number: 27 },
  { id: "ab4", name: "بديل النصر 4", number: 30 },
  { id: "ab5", name: "بديل النصر 5", number: 80 },
];

export const INITIAL_PROFILE: ProfileData = {
  varId: "",
  displayVarId: "",
  displayName: "ناصر السبيعي",
  username: "@nasser",
  bio: "Software Engineer",
  location: "الرياض، السعودية",
  email: "",
  phoneNumber: "055 248 7319",
  profession: "Software Engineer",
  nationalId: "1093478521",
  birthDate: "15/05/1990",
  nationality: "سعودي",
  association: "الهلال",
  leagueClub: "",
  joinDate: "مايو 2026",
  avatarUri: "",
  avatarFrameEnabled: false,
  isVerified: true,
  cardTier: "classic",
  role: "member",
  earnedPoints: 0,
  lockedPredictions: [],
  socialMetrics: {
    xPosts: 0,
    xLikes: 0,
    xReplies: 0,
    xReposts: 0,
    xShares: 0,
    tiktokUploads: 0,
    tiktokLikes: 0,
    tiktokComments: 0,
    tiktokSaves: 0,
    tiktokShares: 0,
    totalInteractions: 0,
  },
  walletPassAdded: false,
  walletPassUrl: getConfiguredWalletPassUrl(),
};
