{
  "files": [
    {
      "path": "src/pages/Login.jsx",
      "content": "import React, { useState } from 'react';\nimport './Login.css';\n\nexport default function Login() {\n  const [form, setForm] = useState({ email: '', password: '' });\n\n  const handleChange = (e) => {\n    setForm({ ...form, [e.target.name]: e.target.value });\n  };\n\n  const handleSubmit = (e) => {\n    e.preventDefault();\n    console.log('Login Data:', form);\n  };\n\n  const handleGoogleLogin = () => {\n    window.location.href = '/auth/google';\n  };\n\n  return (\n    <div className=\"login-page\">\n      <div className=\"login-card\">\n        <div className=\"login-logo\">MyApp</div>\n        <h1 className=\"login-title\">مرحباً بعودتك</h1>\n        <p className=\"login-subtitle\">سجل الدخول للمتابعة إلى حسابك</p>\n\n        <form className=\"login-form\" onSubmit={handleSubmit}>\n          <label className=\"login-label\">البريد الإلكتروني</label>\n          <input\n            type=\"email\"\n            name=\"email\"\n            className=\"login-input\"\n            placeholder=\"example@email.com\"\n            value={form.email}\n            onChange={handleChange}\n            required\n          />\n\n          <label className=\"login-label\">كلمة المرور</label>\n          <input\n            type=\"password\"\n            name=\"password\"\n            className=\"login-input\"\n            placeholder=\"********\"\n            value={form.password}\n            onChange={handleChange}\n            required\n          />\n\n          <button type=\"submit\" className=\"login-button primary-button\">\n            تسجيل الدخول\n          </button>\n        </form>\n\n        <div className=\"login-divider\"><span>أو</span></div>\n\n        <button className=\"login-button google-button\" onClick={handleGoogleLogin}>\n          <span className=\"google-icon\">G</span>\n          تسجيل الدخول عبر Google\n        </button>\n\n        <a href=\"/register\" className=\"login-register-link\">\n          ليس لديك حساب؟ إنشاء حساب جديد\n        </a>\n      </div>\n    </div>\n  );\n}\n"
    },
    {
      "path": "src/pages/Login.css",
      "content": ".login-page {\n  min-height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  background: #f5f7fb;\n  direction: rtl;\n  font-family: Arial, sans-serif;\n}\n\n.login-card {\n  width: 420px;\n  background: #ffffff;\n  padding: 32px;\n  border-radius: 18px;\n  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);\n  box-sizing: border-box;\n}\n\n.login-logo {\n  font-size: 32px;\n  font-weight: 700;\n  color: #1f2937;\n  text-align: center;\n  margin-bottom: 10px;\n}\n\n.login-title {\n  font-size: 24px;\n  font-weight: 700;\n  color: #111827;\n  text-align: center;\n  margin: 0 0 8px;\n}\n\n.login-subtitle {\n  font-size: 14px;\n  color: #6b7280;\n  text-align: center;\n  margin: 0 0 24px;\n}\n\n.login-form {\n  display: flex;\n  flex-direction: column;\n}\n\n.login-label {\n  display: block;\n  margin-bottom: 8px;\n  font-size: 14px;\n  font-weight: 600;\n  color: #374151;\n}\n\n.login-input {\n  width: 100%;\n  padding: 14px;\n  border: 1px solid #d1d5db;\n  border-radius: 12px;\n  font-size: 14px;\n  margin-bottom: 16px;\n  outline: none;\n  box-sizing: border-box;\n}\n\n.login-input:focus {\n  border-color: #2563eb;\n  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.12);\n}\n\n.login-button {\n  width: 100%;\n  padding: 14px;\n  border-radius: 12px;\n  font-size: 15px;\n  font-weight: 600;\n  cursor: pointer;\n  border: none;\n  transition: 0.2s ease;\n}\n\n.primary-button {\n  background: #2563eb;\n  color: #ffffff;\n}\n\n.primary-button:hover {\n  background: #1d4ed8;\n}\n\n.login-divider {\n  display: flex;\n  align-items: center;\n  text-align: center;\n  color: #9ca3af;\n  margin: 20px 0;\n  font-size: 14px;\n}\n\n.login-divider::before,\n.login-divider::after {\n  content: '';\n  flex: 1;\n  border-bottom: 1px solid #e5e7eb;\n}\n\n.login-divider span {\n  padding: 0 10px;\n}\n\n.google-button {\n  background: #ffffff;\n  color: #111827;\n  border: 1px solid #d1d5db;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  gap: 10px;\n}\n\n.google-button:hover {\n  background: #f9fafb;\n}\n\n.google-icon {\n  width: 22px;\n  height: 22px;\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  border-radius: 50%;\n  background: #ffffff;\n  color: #ea4335;\n  font-weight: 700;\n  font-size: 14px;\n}\n\n.login-register-link {\n  display: block;\n  text-align: center;\n  margin-top: 20px;\n  font-size: 14px;\n  color: #2563eb;\n  text-decoration: none;\n}\n\n.login-register-link:hover {\n  text-decoration: underline;\n}\n\n@media (max-width: 480px) {\n  .login-card {\n    width: calc(100% - 24px);\n    padding: 24px;\n  }\n}\n"
    },
    {
      "path": "src/App.jsx",
      "content": "import React from 'react';\nimport Login from './pages/Login';\n\nexport default function App() {\n  return <Login />;\n}\n"
    }
  ]
}